// Full 8-language translations of all data: reasons, categories, items, glossary,
// HOW_TO guides, TERMS, LEGAL_QA, cost calculator, help, compare.
// EN is canonical; missing fields fall back to EN.
import { useMemo } from "react";
import type { Lang } from "./i18n";
import { useLang } from "./i18n";

type Tx = Partial<Record<Lang, string>> & { en: string };
const pick = (t: Tx | undefined, l: Lang): string => (t ? t[l] ?? t.en : "");
const pickArr = (a: Tx[] | undefined, l: Lang): string[] => (a ? a.map((t) => pick(t, l)) : []);

// ------- REASONS -------
type ReasonL = { id: string; emoji: string; label: Tx; description: Tx };
const REASONS_L: ReasonL[] = [
  { id: "study", emoji: "🎓",
    label: { en: "Study", es: "Estudios", fr: "Études", de: "Studium", it: "Studi", pt: "Estudos", pl: "Studia", uk: "Навчання" },
    description: { en: "University, exchange, Erasmus", es: "Universidad, intercambio, Erasmus", fr: "Université, échange, Erasmus", de: "Universität, Austausch, Erasmus", it: "Università, scambio, Erasmus", pt: "Universidade, intercâmbio, Erasmus", pl: "Studia, wymiana, Erasmus", uk: "Університет, обмін, Еразмус" } },
  { id: "work", emoji: "💼",
    label: { en: "Work", es: "Trabajo", fr: "Travail", de: "Arbeit", it: "Lavoro", pt: "Trabalho", pl: "Praca", uk: "Робота" },
    description: { en: "Employment, contract, transfer", es: "Empleo, contrato, traslado", fr: "Emploi, contrat, mutation", de: "Anstellung, Vertrag, Versetzung", it: "Impiego, contratto, trasferimento", pt: "Emprego, contrato, transferência", pl: "Zatrudnienie, kontrakt, transfer", uk: "Робота, контракт, переведення" } },
  { id: "nomad", emoji: "💻",
    label: { en: "Digital nomad", es: "Nómada digital", fr: "Nomade numérique", de: "Digitaler Nomade", it: "Nomade digitale", pt: "Nômade digital", pl: "Cyfrowy nomada", uk: "Цифровий кочівник" },
    description: { en: "Remote work, long-stay visa", es: "Trabajo remoto, visa de larga estancia", fr: "Télétravail, visa long séjour", de: "Remote-Arbeit, Langzeitvisum", it: "Lavoro remoto, visto lunga permanenza", pt: "Trabalho remoto, visto longa estadia", pl: "Praca zdalna, wiza długoterminowa", uk: "Віддалена робота, довгострокова віза" } },
  { id: "family", emoji: "🏡",
    label: { en: "Family", es: "Familia", fr: "Famille", de: "Familie", it: "Famiglia", pt: "Família", pl: "Rodzina", uk: "Сім'я" },
    description: { en: "Reunion, partner, marriage", es: "Reunificación, pareja, matrimonio", fr: "Regroupement, conjoint, mariage", de: "Zusammenführung, Partner, Ehe", it: "Ricongiungimento, partner, matrimonio", pt: "Reagrupamento, parceiro, casamento", pl: "Łączenie, partner, małżeństwo", uk: "Возз'єднання, партнер, шлюб" } },
  { id: "travel", emoji: "✈️",
    label: { en: "Travel", es: "Viaje", fr: "Voyage", de: "Reise", it: "Viaggio", pt: "Viagem", pl: "Podróż", uk: "Подорож" },
    description: { en: "Tourism, long stay", es: "Turismo, larga estancia", fr: "Tourisme, long séjour", de: "Tourismus, Langzeit", it: "Turismo, lunga permanenza", pt: "Turismo, longa estadia", pl: "Turystyka, długi pobyt", uk: "Туризм, тривале перебування" } },
  { id: "refuge", emoji: "🕊️",
    label: { en: "Refuge", es: "Refugio", fr: "Refuge", de: "Zuflucht", it: "Rifugio", pt: "Refúgio", pl: "Schronienie", uk: "Притулок" },
    description: { en: "Asylum, humanitarian", es: "Asilo, humanitario", fr: "Asile, humanitaire", de: "Asyl, humanitär", it: "Asilo, umanitario", pt: "Asilo, humanitário", pl: "Azyl, humanitarny", uk: "Притулок, гуманітарний" } },
];

// ------- CATEGORIES -------
const CATEGORIES_L: Record<string, Tx> = {
  Identity: { en: "Identity", es: "Identidad", fr: "Identité", de: "Identität", it: "Identità", pt: "Identidade", pl: "Tożsamość", uk: "Особа" },
  Visa: { en: "Visa", es: "Visado", fr: "Visa", de: "Visum", it: "Visto", pt: "Visto", pl: "Wiza", uk: "Віза" },
  Housing: { en: "Housing", es: "Vivienda", fr: "Logement", de: "Wohnen", it: "Alloggio", pt: "Habitação", pl: "Mieszkanie", uk: "Житло" },
  Money: { en: "Money", es: "Dinero", fr: "Argent", de: "Geld", it: "Soldi", pt: "Dinheiro", pl: "Pieniądze", uk: "Гроші" },
  Health: { en: "Health", es: "Salud", fr: "Santé", de: "Gesundheit", it: "Salute", pt: "Saúde", pl: "Zdrowie", uk: "Здоров'я" },
  Admin: { en: "Admin", es: "Trámites", fr: "Admin.", de: "Verwaltung", it: "Burocrazia", pt: "Burocracia", pl: "Urzędy", uk: "Адмін" },
};

// ------- CHECKLIST ITEMS (title + description) -------
type ItemL = { title: Tx; description: Tx };
const ITEMS_L: Record<string, ItemL> = {
  passport: {
    title: { en: "Valid passport", es: "Pasaporte válido", fr: "Passeport valide", de: "Gültiger Reisepass", it: "Passaporto valido", pt: "Passaporte válido", pl: "Ważny paszport", uk: "Дійсний паспорт" },
    description: { en: "Must be valid at least 6 months past your stay.", es: "Debe ser válido al menos 6 meses después de tu estancia.", fr: "Doit être valide au moins 6 mois après votre séjour.", de: "Muss mindestens 6 Monate nach Aufenthaltsende gültig sein.", it: "Deve essere valido almeno 6 mesi oltre il soggiorno.", pt: "Deve ser válido pelo menos 6 meses após a sua estadia.", pl: "Musi być ważny co najmniej 6 miesięcy po pobycie.", uk: "Має бути дійсним щонайменше 6 місяців після перебування." } },
  acceptance: {
    title: { en: "University acceptance letter", es: "Carta de admisión", fr: "Lettre d'admission universitaire", de: "Zulassungsbescheid der Universität", it: "Lettera di ammissione", pt: "Carta de aceitação", pl: "List akceptacyjny uczelni", uk: "Лист про зарахування" },
    description: { en: "Original signed letter from your host institution.", es: "Carta original firmada de la institución de acogida.", fr: "Lettre originale signée de l'établissement d'accueil.", de: "Originaldokument der Gastinstitution, unterschrieben.", it: "Lettera originale firmata dall'istituzione ospitante.", pt: "Carta original assinada da instituição de acolhimento.", pl: "Oryginał podpisanego listu od uczelni przyjmującej.", uk: "Оригінал листа з підписом приймаючого закладу." } },
  visa: {
    title: { en: "Student visa / residence permit", es: "Visado de estudiante / permiso de residencia", fr: "Visa étudiant / titre de séjour", de: "Studentenvisum / Aufenthaltstitel", it: "Visto studio / permesso di soggiorno", pt: "Visto de estudante / autorização de residência", pl: "Wiza studencka / zezwolenie na pobyt", uk: "Студентська віза / посвідка на проживання" },
    description: { en: "Apply at the destination embassy in your home country.", es: "Solicítalo en la embajada de destino en tu país.", fr: "Faites la demande à l'ambassade de destination dans votre pays.", de: "Beantragen Sie es bei der Botschaft des Ziellandes.", it: "Richiedilo all'ambasciata di destinazione nel tuo paese.", pt: "Solicite na embaixada do destino no seu país.", pl: "Złóż wniosek w ambasadzie kraju docelowego.", uk: "Подайте заявку в посольство країни призначення." } },
  funds: {
    title: { en: "Proof of financial means", es: "Justificante de medios económicos", fr: "Justificatif de ressources", de: "Finanzierungsnachweis", it: "Prova di mezzi finanziari", pt: "Prova de meios financeiros", pl: "Dowód środków finansowych", uk: "Підтвердження фінансових засобів" },
    description: { en: "Bank statement, blocked account, or scholarship letter.", es: "Extracto bancario, cuenta bloqueada o beca.", fr: "Relevé bancaire, compte bloqué ou bourse.", de: "Kontoauszug, Sperrkonto oder Stipendienschreiben.", it: "Estratto conto, conto bloccato o lettera di borsa.", pt: "Extrato bancário, conta bloqueada ou bolsa.", pl: "Wyciąg bankowy, konto blokowane lub stypendium.", uk: "Виписка з банку, заблокований рахунок або стипендія." } },
  insurance: {
    title: { en: "Health insurance", es: "Seguro médico", fr: "Assurance maladie", de: "Krankenversicherung", it: "Assicurazione sanitaria", pt: "Seguro de saúde", pl: "Ubezpieczenie zdrowotne", uk: "Медичне страхування" },
    description: { en: "Public or recognized private coverage required at registration.", es: "Cobertura pública o privada reconocida al registrarte.", fr: "Couverture publique ou privée reconnue à l'inscription.", de: "Gesetzliche oder anerkannte private Versicherung erforderlich.", it: "Copertura pubblica o privata riconosciuta alla registrazione.", pt: "Cobertura pública ou privada reconhecida no registo.", pl: "Wymagane przy rejestracji ubezpieczenie publiczne lub uznane prywatne.", uk: "Державне або визнане приватне покриття при реєстрації." } },
  housing: {
    title: { en: "Address registration (Anmeldung)", es: "Registro de domicilio (Anmeldung)", fr: "Déclaration de domicile (Anmeldung)", de: "Anmeldung der Adresse", it: "Registrazione di residenza (Anmeldung)", pt: "Registo de morada (Anmeldung)", pl: "Meldunek (Anmeldung)", uk: "Реєстрація адреси (Anmeldung)" },
    description: { en: "Register your address within 14 days of arrival.", es: "Regístrate en los 14 días tras la llegada.", fr: "Déclarez votre adresse dans les 14 jours.", de: "Adresse innerhalb von 14 Tagen nach Einzug anmelden.", it: "Registra l'indirizzo entro 14 giorni dall'arrivo.", pt: "Registe a morada nos 14 dias após chegada.", pl: "Zamelduj się w ciągu 14 dni od przyjazdu.", uk: "Зареєструйте адресу протягом 14 днів після приїзду." } },
  tax: {
    title: { en: "Tax ID number", es: "Número de identificación fiscal", fr: "Numéro fiscal", de: "Steuer-ID", it: "Codice fiscale", pt: "Número de identificação fiscal", pl: "Numer identyfikacji podatkowej", uk: "Податковий номер" },
    description: { en: "Issued automatically after your address registration.", es: "Se emite automáticamente tras el registro de domicilio.", fr: "Délivré automatiquement après la déclaration de domicile.", de: "Wird nach der Anmeldung automatisch zugesandt.", it: "Rilasciato automaticamente dopo la registrazione di residenza.", pt: "Emitido automaticamente após o registo de morada.", pl: "Wydawany automatycznie po zameldowaniu.", uk: "Видається автоматично після реєстрації адреси." } },
  bank: {
    title: { en: "Local bank account", es: "Cuenta bancaria local", fr: "Compte bancaire local", de: "Lokales Bankkonto", it: "Conto bancario locale", pt: "Conta bancária local", pl: "Lokalne konto bankowe", uk: "Місцевий банківський рахунок" },
    description: { en: "Required for rent, salary, and many subscriptions.", es: "Necesario para alquiler, salario y suscripciones.", fr: "Nécessaire pour loyer, salaire et abonnements.", de: "Erforderlich für Miete, Gehalt und Abos.", it: "Necessario per affitto, stipendio e abbonamenti.", pt: "Necessária para renda, salário e assinaturas.", pl: "Wymagane do czynszu, pensji i subskrypcji.", uk: "Потрібен для оренди, зарплати та підписок." } },
  contract: {
    title: { en: "Signed work contract", es: "Contrato de trabajo firmado", fr: "Contrat de travail signé", de: "Unterzeichneter Arbeitsvertrag", it: "Contratto di lavoro firmato", pt: "Contrato de trabalho assinado", pl: "Podpisana umowa o pracę", uk: "Підписаний трудовий договір" },
    description: { en: "Original contract from your employer abroad.", es: "Contrato original de tu empleador en el extranjero.", fr: "Contrat original de votre employeur à l'étranger.", de: "Originalvertrag Ihres Arbeitgebers im Ausland.", it: "Contratto originale dal datore di lavoro all'estero.", pt: "Contrato original do seu empregador no estrangeiro.", pl: "Oryginał umowy od zagranicznego pracodawcy.", uk: "Оригінал договору від іноземного роботодавця." } },
  workpermit: {
    title: { en: "Work permit / visa", es: "Permiso de trabajo / visado", fr: "Permis de travail / visa", de: "Arbeitserlaubnis / Visum", it: "Permesso di lavoro / visto", pt: "Autorização de trabalho / visto", pl: "Pozwolenie na pracę / wiza", uk: "Дозвіл на роботу / віза" },
    description: { en: "Most often sponsored by your employer.", es: "Normalmente patrocinado por el empleador.", fr: "Le plus souvent parrainé par l'employeur.", de: "Meist vom Arbeitgeber gesponsert.", it: "Spesso sponsorizzato dal datore di lavoro.", pt: "Geralmente patrocinado pelo empregador.", pl: "Najczęściej sponsorowane przez pracodawcę.", uk: "Зазвичай спонсорує роботодавець." } },
  qualifications: {
    title: { en: "Recognized qualifications", es: "Cualificaciones reconocidas", fr: "Qualifications reconnues", de: "Anerkannte Qualifikationen", it: "Qualifiche riconosciute", pt: "Qualificações reconhecidas", pl: "Uznane kwalifikacje", uk: "Визнані кваліфікації" },
    description: { en: "Diplomas may need apostille and certified translation.", es: "Los títulos pueden requerir apostilla y traducción jurada.", fr: "Diplômes parfois soumis à apostille et traduction assermentée.", de: "Diplome benötigen oft Apostille und beglaubigte Übersetzung.", it: "I diplomi possono richiedere apostille e traduzione giurata.", pt: "Diplomas podem precisar de apostila e tradução certificada.", pl: "Dyplomy mogą wymagać apostille i tłumaczenia przysięgłego.", uk: "Дипломи можуть потребувати апостиль і завірений переклад." } },
  nomadvisa: {
    title: { en: "Digital nomad visa", es: "Visado de nómada digital", fr: "Visa nomade numérique", de: "Digital-Nomaden-Visum", it: "Visto nomade digitale", pt: "Visto de nómada digital", pl: "Wiza cyfrowego nomady", uk: "Віза цифрового кочівника" },
    description: { en: "Available in select countries; income proof required.", es: "Disponible en algunos países; se exige prueba de ingresos.", fr: "Disponible dans certains pays ; preuve de revenus exigée.", de: "In ausgewählten Ländern; Einkommensnachweis erforderlich.", it: "Disponibile in alcuni paesi; richiesta prova di reddito.", pt: "Em países selecionados; prova de rendimento exigida.", pl: "Dostępna w wybranych krajach; wymagany dowód dochodów.", uk: "Доступна в обраних країнах; потрібен доказ доходу." } },
  income: {
    title: { en: "Proof of remote income", es: "Prueba de ingresos remotos", fr: "Justificatif de revenus en télétravail", de: "Nachweis von Remote-Einkommen", it: "Prova di reddito da remoto", pt: "Prova de rendimento remoto", pl: "Dowód dochodu zdalnego", uk: "Підтвердження віддаленого доходу" },
    description: { en: "Contracts, invoices, or bank statements.", es: "Contratos, facturas o extractos bancarios.", fr: "Contrats, factures ou relevés bancaires.", de: "Verträge, Rechnungen oder Kontoauszüge.", it: "Contratti, fatture o estratti conto.", pt: "Contratos, faturas ou extratos.", pl: "Umowy, faktury lub wyciągi bankowe.", uk: "Контракти, рахунки або виписки." } },
  marriage: {
    title: { en: "Marriage / birth certificates", es: "Certificados de matrimonio / nacimiento", fr: "Actes de mariage / naissance", de: "Heirats-/Geburtsurkunden", it: "Certificati di matrimonio / nascita", pt: "Certidões de casamento / nascimento", pl: "Akty małżeństwa / urodzenia", uk: "Свідоцтва про шлюб / народження" },
    description: { en: "Apostilled and translated.", es: "Apostillados y traducidos.", fr: "Apostillés et traduits.", de: "Mit Apostille und Übersetzung.", it: "Con apostille e traduzione.", pt: "Apostilados e traduzidos.", pl: "Z apostille i tłumaczeniem.", uk: "З апостилем і перекладом." } },
  familyvisa: {
    title: { en: "Family reunification visa", es: "Visado de reagrupación familiar", fr: "Visa de regroupement familial", de: "Familienzusammenführungsvisum", it: "Visto ricongiungimento familiare", pt: "Visto de reagrupamento familiar", pl: "Wiza łączenia rodzin", uk: "Віза возз'єднання сім'ї" },
    description: { en: "Sponsor must meet income and housing thresholds.", es: "El patrocinador debe cumplir requisitos de renta y vivienda.", fr: "Le garant doit remplir des critères de revenus et logement.", de: "Sponsor muss Einkommens- und Wohnvorgaben erfüllen.", it: "Lo sponsor deve soddisfare requisiti di reddito e alloggio.", pt: "Patrocinador deve cumprir requisitos de rendimento e habitação.", pl: "Sponsor musi spełnić wymogi dochodu i mieszkania.", uk: "Спонсор має відповідати критеріям доходу та житла." } },
  return: {
    title: { en: "Return ticket & itinerary", es: "Billete de vuelta e itinerario", fr: "Billet retour et itinéraire", de: "Rückflugticket & Reiseplan", it: "Biglietto di ritorno e itinerario", pt: "Bilhete de regresso e itinerário", pl: "Bilet powrotny i plan podróży", uk: "Зворотний квиток та маршрут" },
    description: { en: "Often requested at border control.", es: "A menudo lo pide el control fronterizo.", fr: "Souvent demandé au contrôle frontalier.", de: "Wird oft an der Grenze verlangt.", it: "Spesso richiesto al controllo di frontiera.", pt: "Frequentemente pedido no controlo de fronteira.", pl: "Często wymagany na granicy.", uk: "Часто запитують на кордоні." } },
  id: {
    title: { en: "Any identification documents", es: "Cualquier documento de identidad", fr: "Toute pièce d'identité disponible", de: "Beliebige Ausweisdokumente", it: "Qualsiasi documento d'identità", pt: "Qualquer documento de identificação", pl: "Dowolne dokumenty tożsamości", uk: "Будь-які документи, що посвідчують особу" },
    description: { en: "Passport, ID, birth certificate — anything available.", es: "Pasaporte, DNI, certificado de nacimiento — lo que tengas.", fr: "Passeport, CNI, acte de naissance — tout ce qui est disponible.", de: "Reisepass, Personalausweis, Geburtsurkunde — alles, was vorhanden ist.", it: "Passaporto, carta d'identità, atto di nascita — qualsiasi cosa.", pt: "Passaporte, BI, certidão de nascimento — o que tiver.", pl: "Paszport, dowód, akt urodzenia — cokolwiek.", uk: "Паспорт, ID-картка, свідоцтво — будь-що." } },
  asylum: {
    title: { en: "Asylum application", es: "Solicitud de asilo", fr: "Demande d'asile", de: "Asylantrag", it: "Domanda di asilo", pt: "Pedido de asilo", pl: "Wniosek o azyl", uk: "Заява про притулок" },
    description: { en: "Apply at the border or first official authority.", es: "Solicítalo en la frontera o la primera autoridad oficial.", fr: "Demandez-le à la frontière ou à la première autorité officielle.", de: "An der Grenze oder bei der ersten Behörde stellen.", it: "Presentala alla frontiera o alla prima autorità ufficiale.", pt: "Apresente na fronteira ou primeira autoridade.", pl: "Złóż na granicy lub w pierwszym urzędzie.", uk: "Подайте на кордоні або в першому офіційному органі." } },
  register: {
    title: { en: "Registration with authorities", es: "Registro con las autoridades", fr: "Enregistrement auprès des autorités", de: "Registrierung bei Behörden", it: "Registrazione presso le autorità", pt: "Registo nas autoridades", pl: "Rejestracja w urzędach", uk: "Реєстрація в органах влади" },
    description: { en: "You will receive a temporary protection certificate.", es: "Recibirás un certificado de protección temporal.", fr: "Vous recevrez une attestation de protection temporaire.", de: "Sie erhalten eine Bescheinigung über vorübergehenden Schutz.", it: "Riceverai un certificato di protezione temporanea.", pt: "Receberá um certificado de proteção temporária.", pl: "Otrzymasz zaświadczenie o ochronie tymczasowej.", uk: "Ви отримаєте посвідчення тимчасового захисту." } },
  health: {
    title: { en: "Health screening", es: "Examen médico", fr: "Examen médical", de: "Gesundheitsuntersuchung", it: "Visita medica", pt: "Triagem de saúde", pl: "Badania zdrowotne", uk: "Медичний огляд" },
    description: { en: "Free basic care provided to registered applicants.", es: "Atención básica gratuita para personas registradas.", fr: "Soins de base gratuits pour les demandeurs enregistrés.", de: "Kostenlose Grundversorgung für registrierte Antragsteller.", it: "Cure base gratuite per i richiedenti registrati.", pt: "Cuidados básicos gratuitos para requerentes registados.", pl: "Bezpłatna podstawowa opieka dla zarejestrowanych.", uk: "Безкоштовна базова допомога для зареєстрованих заявників." } },
};

// ------- GLOSSARY -------
type GlossL = { id: string; term: Tx; meaning: Tx };
const GLOSSARY_L: GlossL[] = [
  { id: "apostille",
    term: { en: "Apostille", es: "Apostilla", fr: "Apostille", de: "Apostille", it: "Apostille", pt: "Apostila", pl: "Apostille", uk: "Апостиль" },
    meaning: { en: "An international stamp that certifies a document is genuine, accepted in 120+ countries.", es: "Un sello internacional que certifica que un documento es auténtico, aceptado en 120+ países.", fr: "Un tampon international qui certifie l'authenticité d'un document, accepté dans plus de 120 pays.", de: "Ein internationaler Stempel, der die Echtheit eines Dokuments bestätigt; in 120+ Ländern anerkannt.", it: "Un timbro internazionale che certifica l'autenticità di un documento, accettato in 120+ paesi.", pt: "Um carimbo internacional que certifica a autenticidade de um documento, aceite em 120+ países.", pl: "Międzynarodowa pieczęć potwierdzająca autentyczność dokumentu, uznawana w 120+ krajach.", uk: "Міжнародний штамп, що засвідчує справжність документа, прийнятий у 120+ країнах." } },
  { id: "anmeldung",
    term: { en: "Anmeldung", es: "Anmeldung", fr: "Anmeldung", de: "Anmeldung", it: "Anmeldung", pt: "Anmeldung", pl: "Anmeldung", uk: "Anmeldung" },
    meaning: { en: "German address registration. Required within 14 days of moving in.", es: "Registro de domicilio alemán. Obligatorio en 14 días tras mudarse.", fr: "Déclaration de domicile allemande. Obligatoire sous 14 jours après l'emménagement.", de: "Deutsche Wohnsitzanmeldung. Innerhalb von 14 Tagen nach Einzug erforderlich.", it: "Registrazione di residenza tedesca. Obbligatoria entro 14 giorni dal trasloco.", pt: "Registo de morada na Alemanha. Obrigatório nos 14 dias após mudança.", pl: "Niemiecki meldunek. Wymagany w 14 dni od wprowadzenia się.", uk: "Реєстрація адреси в Німеччині. Обов'язкова протягом 14 днів після переїзду." } },
  { id: "finmeans",
    term: { en: "Proof of financial means", es: "Justificante de medios económicos", fr: "Justificatif de ressources", de: "Finanzierungsnachweis", it: "Prova di mezzi finanziari", pt: "Prova de meios financeiros", pl: "Dowód środków finansowych", uk: "Підтвердження фінансових засобів" },
    meaning: { en: "Documents showing you can support yourself financially while abroad.", es: "Documentos que muestran que puedes mantenerte económicamente en el extranjero.", fr: "Documents prouvant que vous pouvez subvenir à vos besoins à l'étranger.", de: "Dokumente, die belegen, dass Sie sich im Ausland finanzieren können.", it: "Documenti che dimostrano che puoi mantenerti all'estero.", pt: "Documentos a provar que se pode sustentar no estrangeiro.", pl: "Dokumenty pokazujące, że utrzymasz się za granicą.", uk: "Документи, що підтверджують вашу спроможність утримувати себе за кордоном." } },
  { id: "respermit",
    term: { en: "Residence permit", es: "Permiso de residencia", fr: "Titre de séjour", de: "Aufenthaltstitel", it: "Permesso di soggiorno", pt: "Autorização de residência", pl: "Zezwolenie na pobyt", uk: "Посвідка на проживання" },
    meaning: { en: "Official authorization to live in a country for an extended period.", es: "Autorización oficial para vivir en un país por un periodo prolongado.", fr: "Autorisation officielle de vivre dans un pays pour une durée prolongée.", de: "Offizielle Erlaubnis, längere Zeit in einem Land zu leben.", it: "Autorizzazione ufficiale a vivere in un paese per un periodo prolungato.", pt: "Autorização oficial para viver num país por período prolongado.", pl: "Oficjalne pozwolenie na dłuższy pobyt w kraju.", uk: "Офіційний дозвіл на тривале проживання в країні." } },
  { id: "schengen",
    term: { en: "Schengen", es: "Schengen", fr: "Schengen", de: "Schengen", it: "Schengen", pt: "Schengen", pl: "Schengen", uk: "Шенген" },
    meaning: { en: "A zone of 29 European countries with no internal border checks.", es: "Zona de 29 países europeos sin controles fronterizos internos.", fr: "Une zone de 29 pays européens sans contrôles aux frontières internes.", de: "Eine Zone von 29 europäischen Ländern ohne Binnengrenzkontrollen.", it: "Una zona di 29 paesi europei senza controlli alle frontiere interne.", pt: "Zona de 29 países europeus sem controlos fronteiriços internos.", pl: "Strefa 29 europejskich krajów bez wewnętrznych kontroli granicznych.", uk: "Зона з 29 європейських країн без внутрішнього прикордонного контролю." } },
  { id: "taxres",
    term: { en: "Tax residency", es: "Residencia fiscal", fr: "Résidence fiscale", de: "Steuerresidenz", it: "Residenza fiscale", pt: "Residência fiscal", pl: "Rezydencja podatkowa", uk: "Податкове резидентство" },
    meaning: { en: "The country that has the right to tax your worldwide income, usually based on the 183-day rule.", es: "El país que tiene derecho a gravar tu renta mundial, normalmente según la regla de 183 días.", fr: "Le pays qui peut imposer vos revenus mondiaux, généralement selon la règle des 183 jours.", de: "Das Land, das Ihr weltweites Einkommen besteuern darf — meist nach der 183-Tage-Regel.", it: "Il paese che ha diritto a tassare il tuo reddito globale, di solito in base alla regola dei 183 giorni.", pt: "O país com direito de tributar o seu rendimento global, geralmente pela regra dos 183 dias.", pl: "Kraj, który może opodatkować Twój globalny dochód, zwykle wg reguły 183 dni.", uk: "Країна, яка має право оподатковувати ваш світовий дохід (зазвичай за правилом 183 днів)." } },
];

// ------- HOW_TO -------
type HowL = { where: Tx; steps: Tx[]; forgotten: Tx[]; cost: Tx; tip?: Tx };
const HOWTO_L: Record<string, HowL> = {
  passport: {
    where: { en: "Your home country's passport office, embassy, or consulate.", es: "Oficina de pasaportes, embajada o consulado de tu país.", fr: "Bureau des passeports, ambassade ou consulat de votre pays.", de: "Passamt, Botschaft oder Konsulat Ihres Heimatlandes.", it: "Ufficio passaporti, ambasciata o consolato del tuo paese.", pt: "Repartição de passaportes, embaixada ou consulado do seu país.", pl: "Urząd paszportowy, ambasada lub konsulat Twojego kraju.", uk: "Паспортний стіл, посольство або консульство вашої країни." },
    steps: [
      { en: "Book an appointment online (slots fill weeks in advance).", es: "Reserva cita online (los huecos se llenan con semanas).", fr: "Prenez rendez-vous en ligne (créneaux pris des semaines à l'avance).", de: "Termin online buchen (Plätze sind Wochen im Voraus belegt).", it: "Prenota un appuntamento online (i posti finiscono settimane prima).", pt: "Marque online (vagas esgotam semanas antes).", pl: "Zarezerwuj termin online (miejsca znikają tygodnie wcześniej).", uk: "Запишіться онлайн (місця бронюють за тижні)." },
      { en: "Gather: birth certificate, ID, biometric photo, old passport.", es: "Reúne: partida de nacimiento, DNI, foto biométrica, pasaporte anterior.", fr: "Préparez : acte de naissance, CNI, photo biométrique, ancien passeport.", de: "Sammeln: Geburtsurkunde, Ausweis, biometrisches Foto, alter Pass.", it: "Raccogli: certificato di nascita, ID, foto biometrica, vecchio passaporto.", pt: "Reúna: certidão, BI, foto biométrica, passaporte antigo.", pl: "Przygotuj: akt urodzenia, dowód, zdjęcie biometryczne, stary paszport.", uk: "Зберіть: свідоцтво про народження, ID, біометричне фото, старий паспорт." },
      { en: "Pay the issuance fee and submit fingerprints in person.", es: "Paga la tasa y entrega huellas en persona.", fr: "Payez les frais et faites prendre vos empreintes sur place.", de: "Gebühr zahlen und Fingerabdrücke vor Ort abgeben.", it: "Paga la tassa e fai impronte di persona.", pt: "Pague a taxa e dê impressões digitais presencialmente.", pl: "Zapłać opłatę i oddaj odciski palców osobiście.", uk: "Сплатіть мито та здайте відбитки особисто." },
      { en: "Pick up or receive by mail in 2–6 weeks (rush options exist).", es: "Recoge o recibe por correo en 2–6 semanas (hay urgente).", fr: "Récupérez ou recevez par courrier en 2–6 semaines (option urgente).", de: "Abholen oder per Post in 2–6 Wochen erhalten (Express möglich).", it: "Ritira o ricevi per posta in 2–6 settimane (esiste opzione urgente).", pt: "Recolha ou receba pelo correio em 2–6 semanas (urgente disponível).", pl: "Odbierz lub otrzymaj pocztą w 2–6 tyg. (jest opcja ekspres).", uk: "Заберіть або отримайте поштою за 2–6 тижнів (є експрес)." },
    ],
    forgotten: [
      { en: "Photo size rules differ per country", es: "Los tamaños de foto varían por país", fr: "Les formats photo varient selon les pays", de: "Fotomaße sind länderspezifisch", it: "Le misure foto cambiano per paese", pt: "Tamanhos de foto variam por país", pl: "Rozmiary zdjęć różnią się w krajach", uk: "Розміри фото відрізняються в країнах" },
      { en: "Validity must extend 6+ months past your stay", es: "Validez debe superar tu estancia en 6+ meses", fr: "Validité 6+ mois après votre séjour", de: "Gültigkeit 6+ Monate über Aufenthalt hinaus", it: "Validità 6+ mesi oltre il soggiorno", pt: "Validade 6+ meses após estadia", pl: "Ważność 6+ mies. po pobycie", uk: "Дійсність 6+ міс. після перебування" },
    ],
    cost: { en: "€50–€150", es: "50–150 €", fr: "50–150 €", de: "50–150 €", it: "50–150 €", pt: "50–150 €", pl: "50–150 €", uk: "50–150 €" },
    tip: { en: "Scan every page and store an encrypted copy in cloud and on your phone.", es: "Escanea cada página y guarda copia cifrada en la nube y el móvil.", fr: "Scannez chaque page et conservez une copie chiffrée dans le cloud et sur votre téléphone.", de: "Jede Seite scannen und verschlüsselt in Cloud + Handy speichern.", it: "Scansiona ogni pagina e conserva una copia cifrata su cloud e telefono.", pt: "Digitalize cada página e guarde cópia cifrada na nuvem e no telemóvel.", pl: "Zeskanuj każdą stronę i trzymaj zaszyfrowaną kopię w chmurze i telefonie.", uk: "Скануйте кожну сторінку та зберігайте шифровану копію в хмарі й телефоні." },
  },
  acceptance: {
    where: { en: "Your host university's international office.", es: "Oficina internacional de tu universidad de acogida.", fr: "Bureau international de votre université d'accueil.", de: "International Office Ihrer Gasthochschule.", it: "Ufficio internazionale dell'università ospitante.", pt: "Gabinete internacional da universidade de acolhimento.", pl: "Biuro międzynarodowe uczelni przyjmującej.", uk: "Міжнародний відділ приймаючого ВНЗ." },
    steps: [
      { en: "Confirm enrollment and pay any deposit required.", es: "Confirma matrícula y paga el depósito si lo hay.", fr: "Confirmez l'inscription et payez l'éventuel acompte.", de: "Einschreibung bestätigen und ggf. Anzahlung leisten.", it: "Conferma iscrizione e versa l'eventuale caparra.", pt: "Confirme matrícula e pague depósito se exigido.", pl: "Potwierdź zapis i zapłać zaliczkę.", uk: "Підтвердіть зарахування та сплатіть депозит, якщо є." },
      { en: "Request the official admission letter — original signed and stamped.", es: "Pide la carta de admisión original firmada y sellada.", fr: "Demandez la lettre d'admission originale signée et tamponnée.", de: "Offizielle Zulassung anfordern — Original, unterzeichnet & gestempelt.", it: "Richiedi la lettera ufficiale firmata e timbrata.", pt: "Peça a carta oficial original assinada e carimbada.", pl: "Poproś o oryginał listu z podpisem i pieczęcią.", uk: "Запросіть оригінал листа з підписом і печаткою." },
      { en: "Ask for an extra copy in English for visa purposes.", es: "Pide una copia extra en inglés para el visado.", fr: "Demandez un exemplaire en anglais pour le visa.", de: "Eine Extra-Kopie auf Englisch fürs Visum anfordern.", it: "Chiedi una copia in inglese per il visto.", pt: "Peça uma cópia em inglês para o visto.", pl: "Poproś o dodatkową kopię po angielsku do wizy.", uk: "Попросіть копію англійською для візи." },
      { en: "Have it shipped or download a verifiable PDF.", es: "Pídelo por correo o descarga un PDF verificable.", fr: "Faites-la envoyer ou téléchargez un PDF vérifiable.", de: "Per Post versenden lassen oder verifizierbares PDF herunterladen.", it: "Fattela spedire o scarica un PDF verificabile.", pt: "Envie pelo correio ou descarregue um PDF verificável.", pl: "Wyślij pocztą lub pobierz weryfikowalny PDF.", uk: "Замовте поштою або завантажте перевірний PDF." },
    ],
    forgotten: [
      { en: "Some embassies require the original on paper, not a scan", es: "Algunas embajadas exigen el original, no un escaneo", fr: "Certaines ambassades exigent l'original papier", de: "Manche Botschaften verlangen das Originalpapier", it: "Alcune ambasciate vogliono l'originale cartaceo", pt: "Algumas embaixadas exigem o original em papel", pl: "Niektóre ambasady wymagają oryginału papierowego", uk: "Деякі посольства вимагають оригінал на папері" },
    ],
    cost: { en: "Free (deposit may apply)", es: "Gratis (puede haber depósito)", fr: "Gratuit (acompte possible)", de: "Kostenlos (Anzahlung möglich)", it: "Gratis (può richiedere caparra)", pt: "Grátis (pode haver depósito)", pl: "Bezpłatnie (zaliczka możliwa)", uk: "Безкоштовно (можливий депозит)" },
  },
  visa: {
    where: { en: "The destination country's embassy or consulate in your home country.", es: "Embajada o consulado del país de destino en tu país.", fr: "Ambassade ou consulat du pays de destination dans votre pays.", de: "Botschaft/Konsulat des Ziellandes in Ihrem Heimatland.", it: "Ambasciata o consolato del paese di destinazione nel tuo paese.", pt: "Embaixada/consulado do país de destino no seu país.", pl: "Ambasada lub konsulat kraju docelowego w Twoim kraju.", uk: "Посольство або консульство країни призначення." },
    steps: [
      { en: "Check the exact visa category on the embassy's official site.", es: "Verifica la categoría de visado en la web oficial.", fr: "Vérifiez la catégorie exacte de visa sur le site officiel.", de: "Genaue Visumkategorie auf der offiziellen Website prüfen.", it: "Verifica la categoria sul sito ufficiale.", pt: "Verifique a categoria no site oficial.", pl: "Sprawdź dokładną kategorię na stronie ambasady.", uk: "Перевірте точну категорію візи на офіційному сайті." },
      { en: "Book the appointment — slots can be 4–8 weeks out.", es: "Reserva la cita — los huecos pueden ir a 4–8 semanas.", fr: "Prenez rendez-vous — créneaux à 4–8 semaines.", de: "Termin buchen — Wartezeit 4–8 Wochen.", it: "Prenota — slot anche a 4–8 settimane.", pt: "Marque — vagas a 4–8 semanas.", pl: "Zarezerwuj — terminy 4–8 tygodni.", uk: "Запишіться — слоти за 4–8 тижнів." },
      { en: "Prepare: passport, photos, acceptance/contract, funds proof, insurance, application form.", es: "Prepara: pasaporte, fotos, admisión/contrato, fondos, seguro, formulario.", fr: "Préparez : passeport, photos, admission/contrat, ressources, assurance, formulaire.", de: "Vorbereiten: Pass, Fotos, Zulassung/Vertrag, Finanznachweis, Versicherung, Antrag.", it: "Prepara: passaporto, foto, ammissione/contratto, fondi, assicurazione, modulo.", pt: "Prepare: passaporte, fotos, admissão/contrato, fundos, seguro, formulário.", pl: "Przygotuj: paszport, zdjęcia, list/umowa, środki, ubezpieczenie, wniosek.", uk: "Підготуйте: паспорт, фото, зарахування/контракт, кошти, страхування, анкета." },
      { en: "Attend the interview, submit biometrics, pay the fee.", es: "Asiste a la entrevista, da biometría, paga la tasa.", fr: "Présentez-vous, donnez vos biométries, payez.", de: "Interview, Biometrie, Gebühr.", it: "Vai al colloquio, biometria, paga.", pt: "Vá à entrevista, biometria, pague.", pl: "Idź na rozmowę, biometria, opłata.", uk: "Прийдіть на інтерв'ю, біометрія, сплата." },
      { en: "Track your application; collect the visa sticker when ready.", es: "Sigue el trámite; recoge el visado cuando esté listo.", fr: "Suivez la demande ; récupérez le visa quand prêt.", de: "Antrag verfolgen; Visumetikett abholen.", it: "Traccia la pratica; ritira il visto quando pronto.", pt: "Acompanhe; recolha o visto quando pronto.", pl: "Śledź wniosek; odbierz wizę, gdy gotowa.", uk: "Стежте за заявкою; заберіть візу, коли готова." },
    ],
    forgotten: [
      { en: "Apostille on diplomas", es: "Apostilla en diplomas", fr: "Apostille sur les diplômes", de: "Apostille auf Diplomen", it: "Apostille sui diplomi", pt: "Apostila em diplomas", pl: "Apostille na dyplomach", uk: "Апостиль на дипломах" },
      { en: "Certified translations", es: "Traducciones juradas", fr: "Traductions assermentées", de: "Beglaubigte Übersetzungen", it: "Traduzioni giurate", pt: "Traduções certificadas", pl: "Tłumaczenia przysięgłe", uk: "Завірені переклади" },
      { en: "Extra passport photos", es: "Fotos extra de pasaporte", fr: "Photos d'identité supplémentaires", de: "Extra Passfotos", it: "Foto tessera extra", pt: "Fotos extra", pl: "Dodatkowe zdjęcia paszportowe", uk: "Додаткові фото на паспорт" },
    ],
    cost: { en: "€60–€200", es: "60–200 €", fr: "60–200 €", de: "60–200 €", it: "60–200 €", pt: "60–200 €", pl: "60–200 €", uk: "60–200 €" },
    tip: { en: "Apply as early as legally allowed — usually 3 months before travel.", es: "Solicita lo antes posible — normalmente 3 meses antes del viaje.", fr: "Demandez dès que possible — généralement 3 mois avant le voyage.", de: "So früh wie erlaubt beantragen — meist 3 Monate vor Reise.", it: "Richiedi appena consentito — di solito 3 mesi prima.", pt: "Peça assim que permitido — geralmente 3 meses antes.", pl: "Składaj wniosek najwcześniej, jak można — zwykle 3 mies. przed wyjazdem.", uk: "Подавайте якнайраніше — зазвичай за 3 місяці до подорожі." },
  },
  workpermit: {
    where: { en: "Sponsored by your employer through the destination's labor authority.", es: "Patrocinado por tu empleador ante la autoridad laboral.", fr: "Parrainé par votre employeur via l'autorité du travail.", de: "Vom Arbeitgeber bei der Arbeitsbehörde gesponsert.", it: "Sponsorizzato dal datore tramite l'autorità del lavoro.", pt: "Patrocinado pelo empregador via autoridade laboral.", pl: "Sponsorowane przez pracodawcę przez urząd pracy.", uk: "Спонсорує роботодавець через орган праці." },
    steps: [
      { en: "Receive the signed employment contract.", es: "Recibe el contrato firmado.", fr: "Recevez le contrat signé.", de: "Unterschriebenen Arbeitsvertrag erhalten.", it: "Ricevi il contratto firmato.", pt: "Receba o contrato assinado.", pl: "Odbierz podpisaną umowę.", uk: "Отримайте підписаний контракт." },
      { en: "Employer files the work permit / sponsorship application.", es: "El empleador presenta la solicitud de permiso / patrocinio.", fr: "L'employeur dépose la demande de permis/parrainage.", de: "Arbeitgeber stellt Antrag auf Arbeitserlaubnis/Sponsoring.", it: "Il datore presenta la domanda di permesso/sponsorship.", pt: "Empregador apresenta o pedido de autorização/patrocínio.", pl: "Pracodawca składa wniosek o pozwolenie/sponsorship.", uk: "Роботодавець подає заявку на дозвіл/спонсорство." },
      { en: "You apply for the matching work visa at the embassy.", es: "Solicita el visado de trabajo correspondiente en la embajada.", fr: "Demandez le visa de travail correspondant à l'ambassade.", de: "Sie beantragen das passende Arbeitsvisum bei der Botschaft.", it: "Richiedi il visto di lavoro all'ambasciata.", pt: "Solicite o visto correspondente na embaixada.", pl: "Złóż wniosek o odpowiednią wizę pracowniczą w ambasadzie.", uk: "Подайте на відповідну робочу візу в посольстві." },
      { en: "Enter the country and convert to a residence permit on arrival.", es: "Entra al país y convierte en permiso de residencia al llegar.", fr: "Entrez et convertissez en titre de séjour à l'arrivée.", de: "Einreisen und vor Ort in Aufenthaltstitel umwandeln.", it: "Entra nel paese e converti in permesso di soggiorno.", pt: "Entre no país e converta em autorização de residência.", pl: "Wjedź i zamień na zezwolenie na pobyt po przyjeździe.", uk: "В'їдьте та обміняйте на посвідку при прибутті." },
    ],
    forgotten: [
      { en: "Recognition of foreign qualifications", es: "Reconocimiento de títulos extranjeros", fr: "Reconnaissance des diplômes étrangers", de: "Anerkennung ausländischer Abschlüsse", it: "Riconoscimento dei titoli esteri", pt: "Reconhecimento de qualificações estrangeiras", pl: "Uznawanie zagranicznych kwalifikacji", uk: "Визнання іноземних кваліфікацій" },
      { en: "Apostilled diplomas", es: "Diplomas con apostilla", fr: "Diplômes apostillés", de: "Diplome mit Apostille", it: "Diplomi con apostille", pt: "Diplomas apostilados", pl: "Dyplomy z apostille", uk: "Дипломи з апостилем" },
    ],
    cost: { en: "€100–€400 (often paid by employer)", es: "100–400 € (a menudo paga el empleador)", fr: "100–400 € (souvent payés par l'employeur)", de: "100–400 € (oft vom Arbeitgeber bezahlt)", it: "100–400 € (spesso paga il datore)", pt: "100–400 € (muitas vezes pago pelo empregador)", pl: "100–400 € (często płaci pracodawca)", uk: "100–400 € (часто оплачує роботодавець)" },
  },
  contract: {
    where: { en: "From your employer's HR department.", es: "Del departamento de RR. HH. del empleador.", fr: "Du service RH de votre employeur.", de: "Von der Personalabteilung Ihres Arbeitgebers.", it: "Dal reparto HR del datore.", pt: "Do RH do seu empregador.", pl: "Z działu HR pracodawcy.", uk: "Від відділу кадрів роботодавця." },
    steps: [
      { en: "Negotiate salary, role, start date, and relocation support.", es: "Negocia salario, puesto, fecha de inicio y apoyo de mudanza.", fr: "Négociez salaire, poste, date de début et aide à la relocation.", de: "Gehalt, Rolle, Startdatum und Umzugshilfe verhandeln.", it: "Negozia stipendio, ruolo, data inizio, supporto trasloco.", pt: "Negocie salário, função, data início e apoio de mudança.", pl: "Negocjuj pensję, stanowisko, datę startu i wsparcie relokacji.", uk: "Узгодьте зарплату, посаду, дату початку, підтримку переїзду." },
      { en: "Request the signed contract in writing — PDF and original.", es: "Pide el contrato firmado por escrito — PDF y original.", fr: "Demandez le contrat signé écrit — PDF et original.", de: "Schriftlichen Vertrag verlangen — PDF und Original.", it: "Chiedi il contratto scritto firmato — PDF e originale.", pt: "Peça o contrato escrito assinado — PDF e original.", pl: "Poproś o umowę pisemną — PDF i oryginał.", uk: "Запросіть письмовий підписаний контракт — PDF і оригінал." },
      { en: "Have it translated if not in an official language of the destination.", es: "Tradúcelo si no está en idioma oficial del destino.", fr: "Faites-le traduire si ce n'est pas dans une langue officielle.", de: "Übersetzen lassen, falls nicht in Amtssprache.", it: "Fallo tradurre se non in lingua ufficiale.", pt: "Traduza se não estiver em língua oficial.", pl: "Przetłumacz, jeśli nie w języku urzędowym.", uk: "Перекладіть, якщо не офіційною мовою." },
    ],
    forgotten: [
      { en: "Probation clause", es: "Cláusula de prueba", fr: "Clause de période d'essai", de: "Probezeit-Klausel", it: "Clausola di prova", pt: "Cláusula de período experimental", pl: "Klauzula okresu próbnego", uk: "Випробувальний строк" },
      { en: "Notice period", es: "Plazo de preaviso", fr: "Préavis", de: "Kündigungsfrist", it: "Periodo di preavviso", pt: "Aviso prévio", pl: "Okres wypowiedzenia", uk: "Строк попередження" },
      { en: "Relocation allowance", es: "Bono de relocalización", fr: "Indemnité de relocation", de: "Umzugskostenpauschale", it: "Indennità di trasloco", pt: "Subsídio de relocação", pl: "Dodatek relokacyjny", uk: "Виплата на переїзд" },
    ],
    cost: { en: "Free", es: "Gratis", fr: "Gratuit", de: "Kostenlos", it: "Gratis", pt: "Grátis", pl: "Bezpłatnie", uk: "Безкоштовно" },
  },
};
