// Full 8-language translations for TERMS, LEGAL_QA, COST presets/rows, COMPARE rows, HELP page.
// EN is canonical; missing fields fall back to EN.
import { useMemo } from "react";
import type { Lang } from "./i18n";
import { useLang } from "./i18n";

type Tx = Partial<Record<Lang, string>> & { en: string };
const pk = (t: Tx | undefined, l: Lang): string => (t ? t[l] ?? t.en : "");

// ------- TERMS -------
export type TermL = {
  id: string;
  term: Tx;
  bureaucratic: Tx;
  plain: Tx;
  example?: Tx;
  aliases?: string[];
};

const TERMS_L: TermL[] = [
  { id: "accommodation",
    aliases: ["evidence of accommodation", "housing proof", "alojamiento", "logement", "Unterkunft"],
    term: { en: "Proof of accommodation", es: "Justificante de alojamiento", fr: "Justificatif de logement", de: "Unterkunftsnachweis", it: "Prova di alloggio", pt: "Comprovativo de alojamento", pl: "Dowód zakwaterowania", uk: "Підтвердження житла" },
    bureaucratic: { en: "Provide evidence of accommodation for the duration of your stay.", es: "Acredite alojamiento durante toda su estancia.", fr: "Fournir un justificatif de logement pour toute la durée du séjour.", de: "Nachweis einer Unterkunft für die gesamte Aufenthaltsdauer.", it: "Fornire prova di alloggio per l'intera durata del soggiorno.", pt: "Apresente prova de alojamento para toda a estadia.", pl: "Przedstaw dowód zakwaterowania na cały pobyt.", uk: "Подайте підтвердження житла на весь період перебування." },
    plain: { en: "Show proof of where you'll stay — a rental contract, dorm acceptance letter, or hotel booking.", es: "Muestra dónde vas a vivir: contrato, carta de residencia o reserva de hotel.", fr: "Montrez où vous logerez : bail, lettre de résidence universitaire ou réservation d'hôtel.", de: "Zeige, wo du wohnen wirst — Mietvertrag, Wohnheimzusage oder Hotelbuchung.", it: "Mostra dove starai: contratto d'affitto, lettera dello studentato o prenotazione hotel.", pt: "Mostre onde vai ficar — contrato, carta de residência ou reserva.", pl: "Pokaż gdzie zamieszkasz — umowa najmu, akademik lub rezerwacja hotelu.", uk: "Покажіть де житимете — оренда, гуртожиток або готель." },
    example: { en: "Lease agreement, university dorm letter, Airbnb confirmation.", es: "Contrato de alquiler, carta de residencia, reserva de Airbnb.", fr: "Bail, lettre du CROUS, confirmation Airbnb.", de: "Mietvertrag, Wohnheimbestätigung, Airbnb-Buchung.", it: "Contratto, lettera studentato, conferma Airbnb.", pt: "Contrato, carta da residência, reserva Airbnb.", pl: "Umowa najmu, akademik, rezerwacja Airbnb.", uk: "Договір оренди, гуртожиток, бронь Airbnb." } },
  { id: "finmeans",
    aliases: ["sufficient means", "financial subsistence"],
    term: { en: "Proof of financial means", es: "Justificante de medios económicos", fr: "Justificatif de ressources", de: "Finanzierungsnachweis", it: "Prova di mezzi finanziari", pt: "Prova de meios financeiros", pl: "Dowód środków finansowych", uk: "Підтвердження фінансових засобів" },
    bureaucratic: { en: "Demonstrate sufficient means of subsistence.", es: "Demuestre medios suficientes de subsistencia.", fr: "Démontrer des moyens de subsistance suffisants.", de: "Ausreichende Mittel zum Lebensunterhalt nachweisen.", it: "Dimostrare mezzi di sussistenza sufficienti.", pt: "Comprove meios de subsistência suficientes.", pl: "Wykaż wystarczające środki na utrzymanie.", uk: "Доведіть достатні засоби існування." },
    plain: { en: "Show you have enough money to live there without working illegally.", es: "Demuestra que tienes dinero para vivir sin trabajar ilegalmente.", fr: "Montrez que vous avez assez d'argent pour vivre sans travailler illégalement.", de: "Zeige, dass du genug Geld zum Leben hast, ohne schwarz zu arbeiten.", it: "Dimostra di avere abbastanza denaro per vivere senza lavorare in nero.", pt: "Mostre que tem dinheiro para viver sem trabalhar ilegalmente.", pl: "Pokaż, że masz pieniądze, by żyć bez nielegalnej pracy.", uk: "Покажіть, що маєте кошти на життя без нелегальної роботи." },
    example: { en: "Bank statements, scholarship letter, blocked account (Sperrkonto).", es: "Extractos, carta de beca, cuenta bloqueada (Sperrkonto).", fr: "Relevés, bourse, compte bloqué (Sperrkonto).", de: "Kontoauszüge, Stipendium, Sperrkonto.", it: "Estratti, borsa, conto bloccato (Sperrkonto).", pt: "Extratos, bolsa, conta bloqueada (Sperrkonto).", pl: "Wyciągi, stypendium, konto blokowane (Sperrkonto).", uk: "Виписки, стипендія, заблокований рахунок (Sperrkonto)." } },
  { id: "apostille",
    term: { en: "Apostille", es: "Apostilla", fr: "Apostille", de: "Apostille", it: "Apostille", pt: "Apostila", pl: "Apostille", uk: "Апостиль" },
    bureaucratic: { en: "Documents must be duly legalized via apostille per the 1961 Hague Convention.", es: "Los documentos deben legalizarse mediante apostilla (Convención de La Haya 1961).", fr: "Les documents doivent être légalisés par apostille (Convention de La Haye 1961).", de: "Dokumente sind per Apostille gemäß Haager Übereinkommen 1961 zu legalisieren.", it: "I documenti devono essere legalizzati con apostille (Convenzione dell'Aja 1961).", pt: "Documentos legalizados por apostila (Convenção de Haia de 1961).", pl: "Dokumenty muszą być legalizowane apostille (Konwencja Haska 1961).", uk: "Документи легалізують апостилем (Гаазька конвенція 1961)." },
    plain: { en: "Get a special international stamp that proves your document is genuine abroad.", es: "Obtén un sello internacional que prueba que el documento es auténtico fuera.", fr: "Obtenez un tampon international qui prouve que votre document est authentique à l'étranger.", de: "Hol dir einen internationalen Stempel, der dein Dokument im Ausland anerkennt.", it: "Ottieni un timbro internazionale che certifica il documento all'estero.", pt: "Obtenha um carimbo internacional que prova o documento no estrangeiro.", pl: "Załatw międzynarodową pieczęć potwierdzającą autentyczność za granicą.", uk: "Отримайте міжнародний штамп, що підтверджує документ за кордоном." },
    example: { en: "Apostille on your birth certificate from the foreign affairs ministry.", es: "Apostilla en la partida de nacimiento del ministerio de exteriores.", fr: "Apostille sur l'acte de naissance par le ministère des Affaires étrangères.", de: "Apostille auf der Geburtsurkunde vom Außenministerium.", it: "Apostille sul certificato di nascita dal MAE.", pt: "Apostila na certidão emitida pelo MNE.", pl: "Apostille na akcie urodzenia z MSZ.", uk: "Апостиль на свідоцтві про народження від МЗС." } },
  { id: "anmeldung",
    aliases: ["address registration", "Meldebescheinigung"],
    term: { en: "Anmeldung", es: "Anmeldung (empadronamiento)", fr: "Anmeldung (déclaration de domicile)", de: "Anmeldung", it: "Anmeldung (registrazione)", pt: "Anmeldung (registo de morada)", pl: "Anmeldung (meldunek)", uk: "Anmeldung (реєстрація)" },
    bureaucratic: { en: "Register your residence with the competent municipal authority.", es: "Registre su residencia ante la autoridad municipal competente.", fr: "Déclarez votre résidence auprès de la mairie compétente.", de: "Wohnsitz bei der zuständigen Meldebehörde anmelden.", it: "Registra la residenza presso il comune competente.", pt: "Registe a residência na autoridade municipal competente.", pl: "Zamelduj się we właściwym urzędzie gminy.", uk: "Зареєструйте місце проживання в компетентному органі." },
    plain: { en: "Tell the local town hall your new address — usually within 14 days of moving in.", es: "Comunica tu nueva dirección al ayuntamiento — normalmente en 14 días.", fr: "Déclarez votre nouvelle adresse à la mairie — souvent sous 14 jours.", de: "Sag dem Rathaus deine neue Adresse — meist innerhalb von 14 Tagen.", it: "Comunica al comune il nuovo indirizzo — di solito entro 14 giorni.", pt: "Comunique a nova morada à câmara — geralmente em 14 dias.", pl: "Zgłoś nowy adres w urzędzie miasta — zwykle w 14 dni.", uk: "Повідомте міській раді нову адресу — зазвичай протягом 14 днів." },
    example: { en: "Bürgeramt appointment in Germany; Meldezettel in Austria.", es: "Cita en el Bürgeramt (Alemania); Meldezettel en Austria.", fr: "RDV au Bürgeramt (Allemagne) ; Meldezettel en Autriche.", de: "Bürgeramt-Termin in Deutschland; Meldezettel in Österreich.", it: "Bürgeramt in Germania; Meldezettel in Austria.", pt: "Bürgeramt na Alemanha; Meldezettel na Áustria.", pl: "Bürgeramt w Niemczech; Meldezettel w Austrii.", uk: "Bürgeramt у Німеччині; Meldezettel в Австрії." } },
  { id: "respermit",
    aliases: ["Aufenthaltstitel", "titre de séjour", "permesso di soggiorno"],
    term: { en: "Residence permit", es: "Permiso de residencia", fr: "Titre de séjour", de: "Aufenthaltstitel", it: "Permesso di soggiorno", pt: "Autorização de residência", pl: "Zezwolenie na pobyt", uk: "Посвідка на проживання" },
    bureaucratic: { en: "Obtain the corresponding residence title prior to expiry of the visa.", es: "Obtenga el permiso de residencia antes de que caduque el visado.", fr: "Obtenez le titre de séjour avant l'expiration du visa.", de: "Aufenthaltstitel vor Ablauf des Visums beantragen.", it: "Ottieni il permesso prima della scadenza del visto.", pt: "Obtenha a autorização antes da expiração do visto.", pl: "Uzyskaj zezwolenie przed wygaśnięciem wizy.", uk: "Отримайте посвідку до закінчення візи." },
    plain: { en: "Get your long-stay card before your entry visa runs out.", es: "Saca tu tarjeta de larga estancia antes de que caduque tu visado.", fr: "Obtenez votre carte de long séjour avant que le visa n'expire.", de: "Hol dir die Aufenthaltskarte, bevor das Einreisevisum endet.", it: "Ottieni la carta di lungo soggiorno prima che scada il visto.", pt: "Obtenha o cartão de longa duração antes do visto caducar.", pl: "Wyrób kartę pobytu zanim wygaśnie wiza wjazdowa.", uk: "Отримайте картку довгострокового перебування до завершення візи." } },
  { id: "biometrics",
    term: { en: "Biometrics", es: "Biometría", fr: "Biométrie", de: "Biometrie", it: "Biometria", pt: "Biometria", pl: "Biometria", uk: "Біометрія" },
    bureaucratic: { en: "Submit biometric identifiers at the designated VAC.", es: "Entregue identificadores biométricos en el centro VAC designado.", fr: "Soumettez vos identifiants biométriques au centre VAC désigné.", de: "Biometrische Daten im benannten VAC abgeben.", it: "Consegna i dati biometrici al VAC indicato.", pt: "Entregue dados biométricos no VAC indicado.", pl: "Złóż dane biometryczne w wyznaczonym VAC.", uk: "Здайте біометричні дані у вказаному VAC." },
    plain: { en: "Go to the visa center to get your fingerprints and photo taken.", es: "Ve al centro de visados para huellas y foto.", fr: "Allez au centre des visas pour empreintes et photo.", de: "Geh ins Visumzentrum für Fingerabdrücke und Foto.", it: "Vai al centro visti per impronte e foto.", pt: "Vá ao centro de vistos para impressões e foto.", pl: "Idź do centrum wizowego po odciski i zdjęcie.", uk: "Йдіть у візовий центр для відбитків і фото." } },
  { id: "taxres",
    term: { en: "Tax residency", es: "Residencia fiscal", fr: "Résidence fiscale", de: "Steuerresidenz", it: "Residenza fiscale", pt: "Residência fiscal", pl: "Rezydencja podatkowa", uk: "Податкове резидентство" },
    bureaucratic: { en: "You may be deemed tax-resident upon meeting the 183-day threshold.", es: "Puede ser residente fiscal al superar los 183 días.", fr: "Vous pouvez être considéré résident fiscal au-delà de 183 jours.", de: "Bei mehr als 183 Tagen giltst du als steuerlich ansässig.", it: "Oltre i 183 giorni puoi essere residente fiscale.", pt: "Pode ser residente fiscal acima de 183 dias.", pl: "Powyżej 183 dni możesz być rezydentem podatkowym.", uk: "Понад 183 дні — можете стати податковим резидентом." },
    plain: { en: "If you spend more than 183 days a year somewhere, that country can tax all your income.", es: "Si pasas más de 183 días al año en un país, puede gravar todos tus ingresos.", fr: "Au-delà de 183 jours par an, le pays peut imposer tous vos revenus.", de: "Über 183 Tage/Jahr darf das Land dein gesamtes Einkommen besteuern.", it: "Oltre 183 giorni l'anno il paese può tassare tutto il tuo reddito.", pt: "Acima de 183 dias por ano, o país pode tributar todo o seu rendimento.", pl: "Powyżej 183 dni rocznie kraj może opodatkować cały dochód.", uk: "Понад 183 дні на рік країна може оподатковувати весь ваш дохід." } },
  { id: "schengen",
    term: { en: "Schengen Area", es: "Espacio Schengen", fr: "Espace Schengen", de: "Schengen-Raum", it: "Area Schengen", pt: "Espaço Schengen", pl: "Strefa Schengen", uk: "Шенгенська зона" },
    bureaucratic: { en: "Free movement is permitted within the Schengen Area subject to the 90/180 rule.", es: "Libre circulación en Schengen sujeta a la regla 90/180.", fr: "Libre circulation en Schengen selon la règle 90/180.", de: "Freier Verkehr im Schengen-Raum nach der 90/180-Regel.", it: "Libera circolazione in Schengen secondo la regola 90/180.", pt: "Livre circulação em Schengen pela regra 90/180.", pl: "Swobodny ruch w Schengen wg reguły 90/180.", uk: "Вільне пересування у Шенгені за правилом 90/180." },
    plain: { en: "You can travel between 29 European countries without border checks — but only 90 days in any 180.", es: "Puedes viajar entre 29 países europeos sin controles — pero solo 90 días en 180.", fr: "Vous pouvez circuler entre 29 pays européens sans contrôles — 90 jours sur 180.", de: "Du kannst durch 29 EU-Länder ohne Grenzkontrollen reisen — aber nur 90 von 180 Tagen.", it: "Viaggi tra 29 paesi senza controlli — ma solo 90 giorni su 180.", pt: "Viaja entre 29 países sem controlos — mas só 90 dias em 180.", pl: "Możesz podróżować między 29 krajami bez kontroli — ale 90 dni na 180.", uk: "Можна подорожувати між 29 країнами без перевірок — лише 90 із 180 днів." } },
  { id: "legalisation",
    term: { en: "Legalisation", es: "Legalización", fr: "Légalisation", de: "Legalisation", it: "Legalizzazione", pt: "Legalização", pl: "Legalizacja", uk: "Легалізація" },
    bureaucratic: { en: "Documents require consular legalisation.", es: "Los documentos requieren legalización consular.", fr: "Les documents nécessitent une légalisation consulaire.", de: "Dokumente bedürfen konsularischer Legalisation.", it: "I documenti richiedono legalizzazione consolare.", pt: "Documentos requerem legalização consular.", pl: "Dokumenty wymagają legalizacji konsularnej.", uk: "Документи потребують консульської легалізації." },
    plain: { en: "If the country doesn't accept apostilles, the embassy must stamp your document instead.", es: "Si el país no acepta apostilla, la embajada sella el documento.", fr: "Si le pays n'accepte pas l'apostille, l'ambassade tamponne le document.", de: "Wo Apostillen nicht gelten, stempelt die Botschaft.", it: "Se il paese non accetta l'apostille, timbra l'ambasciata.", pt: "Onde a apostila não é aceite, carimba a embaixada.", pl: "Gdy kraj nie uznaje apostille, pieczętuje ambasada.", uk: "Якщо країна не приймає апостиль, штампує посольство." } },
  { id: "sworntr",
    aliases: ["certified translation"],
    term: { en: "Sworn translation", es: "Traducción jurada", fr: "Traduction assermentée", de: "Beglaubigte Übersetzung", it: "Traduzione giurata", pt: "Tradução juramentada", pl: "Tłumaczenie przysięgłe", uk: "Присяжний переклад" },
    bureaucratic: { en: "A sworn translation by an accredited translator is required.", es: "Se requiere traducción jurada por traductor acreditado.", fr: "Une traduction assermentée par un traducteur agréé est requise.", de: "Beglaubigte Übersetzung durch vereidigten Übersetzer.", it: "Traduzione giurata da traduttore accreditato.", pt: "Tradução juramentada por tradutor acreditado.", pl: "Tłumaczenie przysięgłe przez akredytowanego tłumacza.", uk: "Потрібен присяжний переклад акредитованим перекладачем." },
    plain: { en: "An official translator (registered with a court) must translate the document — Google Translate doesn't count.", es: "Un traductor oficial (registrado en juzgado) debe traducir — Google Translate no vale.", fr: "Un traducteur officiel (assermenté) doit traduire — Google Translate ne suffit pas.", de: "Ein vereidigter Übersetzer muss übersetzen — Google Translate zählt nicht.", it: "Solo un traduttore giurato (iscritto al tribunale) — Google Translate non basta.", pt: "Tradutor oficial registado no tribunal — Google Translate não conta.", pl: "Tłumacz przysięgły wpisany na listę sądu — Google Translate się nie liczy.", uk: "Перекладач, акредитований судом — Google Translate не підійде." } },
  { id: "sperrkonto",
    aliases: ["blocked account"],
    term: { en: "Sperrkonto", es: "Sperrkonto (cuenta bloqueada)", fr: "Sperrkonto (compte bloqué)", de: "Sperrkonto", it: "Sperrkonto (conto bloccato)", pt: "Sperrkonto (conta bloqueada)", pl: "Sperrkonto (konto blokowane)", uk: "Sperrkonto (заблокований рахунок)" },
    bureaucratic: { en: "Open a blocked account with a recognised provider.", es: "Abra una cuenta bloqueada con proveedor reconocido.", fr: "Ouvrez un compte bloqué chez un prestataire reconnu.", de: "Sperrkonto bei anerkanntem Anbieter eröffnen.", it: "Apri un conto bloccato presso fornitore riconosciuto.", pt: "Abra conta bloqueada num fornecedor reconhecido.", pl: "Otwórz konto blokowane u uznanego dostawcy.", uk: "Відкрийте заблокований рахунок у визнаного провайдера." },
    plain: { en: "A German bank account that locks your money and releases a monthly allowance — proves you can support yourself as a student.", es: "Cuenta alemana que bloquea tu dinero y libera una asignación mensual — prueba que puedes mantenerte como estudiante.", fr: "Compte allemand qui bloque votre argent et libère une allocation mensuelle — preuve que vous pouvez vivre comme étudiant.", de: "Deutsches Konto, das Geld sperrt und monatlich freigibt — Nachweis für Studierende.", it: "Conto tedesco che blocca i fondi e rilascia un'indennità mensile — prova come studente.", pt: "Conta alemã que bloqueia o dinheiro e liberta mensalmente — prova como estudante.", pl: "Niemieckie konto blokujące pieniądze i wypłacające miesięcznie — dowód dla studenta.", uk: "Німецький рахунок, що блокує гроші і видає щомісяця — доказ для студента." } },
  { id: "vat",
    term: { en: "VAT number", es: "Número de IVA", fr: "Numéro de TVA", de: "Umsatzsteuer-ID", it: "Partita IVA", pt: "Número de IVA", pl: "Numer VAT", uk: "Номер ПДВ" },
    bureaucratic: { en: "Register for a national VAT identification number.", es: "Regístrese para obtener un NIF/IVA nacional.", fr: "Demandez un numéro national de TVA.", de: "Nationale Umsatzsteuer-ID beantragen.", it: "Registra una Partita IVA nazionale.", pt: "Registe um NIF de IVA nacional.", pl: "Zarejestruj krajowy numer VAT.", uk: "Зареєструйте національний номер ПДВ." },
    plain: { en: "If you'll invoice clients as a freelancer, you need a tax number to charge sales tax legally.", es: "Si facturas como freelance, necesitas un número fiscal para cobrar el IVA legalmente.", fr: "Pour facturer en freelance, il faut un numéro fiscal pour la TVA.", de: "Wer als Freelancer Rechnungen schreibt, braucht eine USt-ID.", it: "Per fatturare da freelance serve la partita IVA.", pt: "Para faturar como freelancer precisa de NIF de IVA.", pl: "By fakturować jako freelancer, potrzebujesz VAT.", uk: "Щоб виставляти рахунки фрилансером — потрібен номер ПДВ." } },
  { id: "righttowork",
    term: { en: "Right to work", es: "Derecho a trabajar", fr: "Droit au travail", de: "Arbeitserlaubnis", it: "Diritto al lavoro", pt: "Direito ao trabalho", pl: "Prawo do pracy", uk: "Право на роботу" },
    bureaucratic: { en: "Verify entitlement to engage in remunerated activity.", es: "Verifique el derecho a realizar actividad remunerada.", fr: "Vérifiez le droit d'exercer une activité rémunérée.", de: "Prüfe das Recht auf entgeltliche Tätigkeit.", it: "Verifica il diritto a svolgere attività retribuita.", pt: "Verifique o direito a atividade remunerada.", pl: "Sprawdź prawo do pracy zarobkowej.", uk: "Перевірте право на оплачувану діяльність." },
    plain: { en: "Check whether your visa actually lets you take a paid job — many tourist and student visas don't.", es: "Comprueba si tu visado permite trabajar — muchas de turismo y estudios no.", fr: "Vérifiez si votre visa autorise un emploi rémunéré — beaucoup ne l'autorisent pas.", de: "Prüfe, ob dein Visum bezahlte Arbeit erlaubt — viele Tourist/Student-Visa nicht.", it: "Verifica se il visto consente lavoro retribuito — molti turistici/studio no.", pt: "Veja se o visto permite trabalho — muitos turísticos/estudo não.", pl: "Sprawdź, czy wiza pozwala pracować — wiele turystycznych/studenckich nie.", uk: "Перевірте, чи дозволяє ваша віза оплачувану роботу — багато туристичних/студентських — ні." } },
  { id: "healthins",
    term: { en: "Health insurance certificate", es: "Certificado de seguro médico", fr: "Attestation d'assurance maladie", de: "Krankenversicherungsnachweis", it: "Certificato di assicurazione sanitaria", pt: "Certificado de seguro de saúde", pl: "Zaświadczenie o ubezpieczeniu zdrowotnym", uk: "Довідка про медичне страхування" },
    bureaucratic: { en: "Provide proof of comprehensive health coverage.", es: "Acredite cobertura médica integral.", fr: "Fournir une preuve de couverture santé complète.", de: "Umfassenden Versicherungsschutz nachweisen.", it: "Dimostra copertura sanitaria completa.", pt: "Comprove cobertura de saúde abrangente.", pl: "Udokumentuj pełne ubezpieczenie zdrowotne.", uk: "Доведіть повне медичне покриття." },
    plain: { en: "A document from your insurer showing they'll pay for hospital bills while you're abroad.", es: "Documento de tu aseguradora que muestra que cubrirá hospital en el extranjero.", fr: "Document de votre assureur prouvant la prise en charge à l'étranger.", de: "Nachweis deiner Versicherung, dass Krankenhauskosten im Ausland gedeckt sind.", it: "Documento dell'assicurazione che copre l'ospedale all'estero.", pt: "Documento da seguradora a cobrir hospital no estrangeiro.", pl: "Dokument ubezpieczyciela potwierdzający pokrycie kosztów szpitala.", uk: "Документ страховика про покриття лікарняних витрат за кордоном." } },
  { id: "bgcheck",
    aliases: ["police clearance", "criminal record check"],
    term: { en: "Background check", es: "Antecedentes penales", fr: "Casier judiciaire", de: "Führungszeugnis", it: "Casellario giudiziale", pt: "Registo criminal", pl: "Zaświadczenie o niekaralności", uk: "Довідка про несудимість" },
    bureaucratic: { en: "Submit a recent extract from the criminal record register.", es: "Presente un certificado reciente de antecedentes penales.", fr: "Fournir un extrait récent du casier judiciaire.", de: "Aktuelles Führungszeugnis vorlegen.", it: "Presenta estratto recente del casellario.", pt: "Apresente extrato recente do registo criminal.", pl: "Złóż aktualne zaświadczenie o niekaralności.", uk: "Подайте свіжу довідку про несудимість." },
    plain: { en: "A paper from the police saying you have no criminal record — must be recent (usually under 3 months old).", es: "Papel de la policía sin antecedentes — reciente (menos de 3 meses).", fr: "Document de la police attestant l'absence de casier — récent (<3 mois).", de: "Polizeischreiben über keine Vorstrafen — meist nicht älter als 3 Monate.", it: "Documento della polizia senza precedenti — recente (<3 mesi).", pt: "Documento da polícia sem antecedentes — recente (<3 meses).", pl: "Zaświadczenie z policji o niekaralności — świeże (<3 mies.).", uk: "Поліцейська довідка про несудимість — свіжа (до 3 міс.)." } },
  { id: "family",
    term: { en: "Family reunification", es: "Reagrupación familiar", fr: "Regroupement familial", de: "Familienzusammenführung", it: "Ricongiungimento familiare", pt: "Reagrupamento familiar", pl: "Łączenie rodzin", uk: "Возз'єднання сім'ї" },
    bureaucratic: { en: "Apply under the family reunification provisions.", es: "Solicite por las normas de reagrupación familiar.", fr: "Demandez au titre du regroupement familial.", de: "Antrag nach den Vorschriften zur Familienzusammenführung.", it: "Domanda secondo le norme di ricongiungimento.", pt: "Solicite ao abrigo do reagrupamento.", pl: "Wniosek w ramach łączenia rodzin.", uk: "Подайте за нормами возз'єднання сім'ї." },
    plain: { en: "The visa route for joining a spouse, partner, parent or child who already lives there.", es: "Vía de visado para unirte a cónyuge, pareja, padre o hijo ya residente.", fr: "Voie de visa pour rejoindre un proche déjà résident.", de: "Visumweg, um zu Ehepartner, Eltern oder Kind zu ziehen, die schon dort leben.", it: "Percorso di visto per raggiungere un familiare già residente.", pt: "Via de visto para juntar-se a familiar já residente.", pl: "Ścieżka wizowa do dołączenia do mieszkającego tam bliskiego.", uk: "Шлях візи для возз'єднання з родичем, який вже там живе." } },
  { id: "onward",
    term: { en: "Onward ticket", es: "Billete de salida", fr: "Billet de continuation", de: "Weiterreiseticket", it: "Biglietto di proseguimento", pt: "Bilhete de saída", pl: "Bilet wyjazdowy", uk: "Квиток на виїзд" },
    bureaucratic: { en: "Evidence of onward travel may be required at the border.", es: "Puede pedirse prueba de salida en la frontera.", fr: "Une preuve de continuation peut être exigée à la frontière.", de: "An der Grenze kann ein Weiterreisenachweis verlangt werden.", it: "Alla frontiera può essere richiesto biglietto di proseguimento.", pt: "Pode ser exigida prova de saída na fronteira.", pl: "Na granicy mogą wymagać dowodu wyjazdu.", uk: "На кордоні можуть запитати квиток на виїзд." },
    plain: { en: "Proof you'll leave before your allowed stay ends — usually a return or next-destination flight.", es: "Prueba de que saldrás antes de fin de estancia — vuelo de vuelta o siguiente destino.", fr: "Preuve que vous partirez avant la fin du séjour — vol retour ou suivant.", de: "Nachweis, dass du vor Ablauf ausreist — Rückflug oder Weiterflug.", it: "Prova che uscirai prima della scadenza — volo di ritorno o successivo.", pt: "Prova que vai sair antes do fim — voo de regresso ou seguinte.", pl: "Dowód, że wyjedziesz przed końcem pobytu — lot powrotny lub dalszy.", uk: "Доказ виїзду до завершення терміну — зворотний або наступний рейс." } },
  { id: "overstay",
    term: { en: "Visa overstay", es: "Estancia irregular", fr: "Dépassement de visa", de: "Visumüberschreitung", it: "Permanenza oltre il visto", pt: "Permanência ilegal", pl: "Przekroczenie ważności wizy", uk: "Перевищення терміну візи" },
    bureaucratic: { en: "Overstays may incur entry bans and administrative sanctions.", es: "Las estancias irregulares pueden conllevar prohibiciones y sanciones.", fr: "Le dépassement peut entraîner interdictions et sanctions.", de: "Überschreitungen können Einreisesperren und Bußgelder nach sich ziehen.", it: "Permanenze oltre il visto comportano divieti e sanzioni.", pt: "Permanência ilegal pode levar a banimentos e sanções.", pl: "Przekroczenie skutkuje zakazem wjazdu i karami.", uk: "Перевищення тягне заборону в'їзду та штрафи." },
    plain: { en: "Staying longer than your visa allows — even by one day — can get you banned from re-entering for years.", es: "Quedarte más de lo permitido — aunque un día — puede vetar tu reentrada años.", fr: "Rester plus longtemps que prévu — même un jour — peut entraîner une interdiction de plusieurs années.", de: "Schon ein Tag zu lange kann mehrjährige Einreisesperren bedeuten.", it: "Restare oltre — anche un giorno — può vietarti l'ingresso per anni.", pt: "Ficar além — mesmo um dia — pode banir-te durante anos.", pl: "Nawet jeden dzień ponad termin to wieloletni zakaz wjazdu.", uk: "Навіть один зайвий день — і заборона в'їзду на роки." } },
];

// ------- LEGAL Q&A -------
export type LegalShort = "Yes" | "No" | "It depends" | "Usually yes" | "Usually no";
export type LegalL = { id: string; q: Tx; short: LegalShort; answer: Tx; region?: Tx; source?: { label: string; url: string } };

const LEGAL_L: LegalL[] = [
  { id: "work-student", short: "Usually yes",
    q: { en: "Can I work on a student visa?", es: "¿Puedo trabajar con visado de estudiante?", fr: "Puis-je travailler avec un visa étudiant ?", de: "Darf ich mit Studentenvisum arbeiten?", it: "Posso lavorare con visto studio?", pt: "Posso trabalhar com visto de estudante?", pl: "Czy mogę pracować na wizie studenckiej?", uk: "Чи можу я працювати на студентській візі?" },
    answer: { en: "Most countries allow students to work part-time — typically 15–20 hours per week during term and full-time in holidays. Germany allows 140 full days / 280 half days a year, France 964 hours/year, the Netherlands 16 hours/week, the UK up to 20 hours/week.", es: "La mayoría permite trabajar parcial — normalmente 15–20 h/sem durante el curso y completo en vacaciones. Alemania: 140 días completos/280 medios al año; Francia: 964 h/año; Países Bajos: 16 h/sem; Reino Unido: hasta 20 h/sem.", fr: "La plupart des pays autorisent un emploi à temps partiel — 15–20 h/sem en cours, temps plein en vacances. Allemagne : 140 jours complets/280 demi par an. France : 964 h/an. Pays-Bas : 16 h/sem. Royaume-Uni : 20 h/sem.", de: "Die meisten Länder erlauben Teilzeitarbeit — 15–20 Std./Woche im Semester, Vollzeit in Ferien. DE: 140 ganze / 280 halbe Tage/Jahr; FR: 964 Std./Jahr; NL: 16 Std./Wo.; UK: bis 20 Std./Wo.", it: "Quasi ovunque part-time consentito — 15–20 h/sett. e tempo pieno in vacanza. DE: 140 giorni interi / 280 mezze; FR: 964 h/anno; NL: 16 h/sett.; UK: 20 h/sett.", pt: "Quase todos permitem part-time — 15–20 h/sem em aulas, integral em férias. DE: 140 dias inteiros/280 meios; FR: 964 h/ano; NL: 16 h/sem; UK: 20 h/sem.", pl: "Prawie wszędzie praca w niepełnym wymiarze — 15–20 h/tyg., pełny etat w wakacje. DE: 140/280 dni; FR: 964 h/rok; NL: 16 h/tyg.; UK: 20 h/tyg.", uk: "Зазвичай дозволено часткову зайнятість — 15–20 год/тиж під час семестру, повна — на канікулах. DE: 140/280 днів; FR: 964 год/рік; NL: 16 год/тиж; UK: до 20 год/тиж." },
    source: { label: "EU Immigration Portal", url: "https://immigration-portal.ec.europa.eu/" } },
  { id: "freelance", short: "It depends",
    q: { en: "Can I freelance on a residence permit?", es: "¿Puedo trabajar como freelance con permiso de residencia?", fr: "Puis-je être freelance avec un titre de séjour ?", de: "Darf ich mit Aufenthaltstitel freiberuflich arbeiten?", it: "Posso fare freelance con permesso di soggiorno?", pt: "Posso trabalhar como freelancer com autorização?", pl: "Czy mogę być freelancerem na karcie pobytu?", uk: "Чи можу я фрилансити з посвідкою?" },
    answer: { en: "A standard work or student permit usually only covers a specific employer. To freelance you normally need a self-employment permit (Germany: Freiberufler visa, Spain: cuenta propia, Portugal: D2). Doing freelance work on the wrong permit can void it.", es: "Un permiso normal solo cubre un empleador concreto. Para freelance suele hacer falta un permiso de autónomo (DE: Freiberufler; ES: cuenta propia; PT: D2). Hacerlo con el permiso equivocado puede invalidarlo.", fr: "Un permis classique ne couvre qu'un employeur. Pour freelance, il faut un permis indépendant (DE: Freiberufler ; ES: cuenta propia ; PT: D2). Le faire avec le mauvais permis peut l'annuler.", de: "Standardpermits decken meist nur einen Arbeitgeber. Für Selbstständigkeit braucht es ein Freiberufler-Visum (DE), cuenta propia (ES), D2 (PT). Falscher Permit-Status kann erlöschen.", it: "Un permesso standard copre solo un datore. Per freelance serve permesso da autonomo (DE: Freiberufler; ES: cuenta propia; PT: D2). Lavorare con permesso sbagliato lo annulla.", pt: "Permissão padrão cobre só um empregador. Para freelance precisa de visto de independente (DE Freiberufler, ES cuenta propia, PT D2). Usar errado invalida.", pl: "Standardowy permit obejmuje jednego pracodawcę. Do freelancingu potrzebny osobny status (DE: Freiberufler; ES: cuenta propia; PT: D2).", uk: "Стандартний дозвіл зазвичай — на одного роботодавця. Для фрилансу потрібен окремий статус (DE: Freiberufler; ES: cuenta propia; PT: D2)." } },
  { id: "stay-after-grad", short: "Usually yes",
    q: { en: "Can I stay after graduation?", es: "¿Puedo quedarme tras graduarme?", fr: "Puis-je rester après mes études ?", de: "Darf ich nach dem Studium bleiben?", it: "Posso restare dopo la laurea?", pt: "Posso ficar após formar-me?", pl: "Czy mogę zostać po studiach?", uk: "Чи можу я залишитися після випуску?" },
    answer: { en: "Most EU countries grant a post-study job-search permit of 9–18 months. Germany: 18 months. France: 12 months. Netherlands: 1 year (Zoekjaar). UK: 2-year Graduate visa. You usually have to apply before your student permit expires.", es: "La mayoría de la UE concede permiso de búsqueda de empleo de 9–18 meses. DE: 18; FR: 12; NL: 1 año (Zoekjaar); UK: visado Graduate 2 años. Solicítalo antes de que caduque el permiso de estudios.", fr: "La plupart des pays UE délivrent un permis de recherche d'emploi 9–18 mois. DE: 18 ; FR: 12 ; NL: 1 an (Zoekjaar) ; UK: visa Graduate 2 ans. Demandez avant l'expiration du permis étudiant.", de: "Die meisten EU-Länder bieten 9–18 Monate Arbeitsuchvisum nach dem Studium. DE: 18; FR: 12; NL: 1 Jahr (Zoekjaar); UK: 2 Jahre Graduate. Vor Ablauf des Studentenvisums beantragen.", it: "Quasi tutta la UE concede un permesso post-studio 9–18 mesi. DE: 18; FR: 12; NL: 1 anno (Zoekjaar); UK: 2 anni Graduate. Richiedi prima della scadenza.", pt: "Quase toda a UE concede permissão pós-estudo 9–18 meses. DE: 18; FR: 12; NL: 1 ano; UK: 2 anos Graduate.", pl: "UE zwykle daje 9–18 mies. na szukanie pracy po studiach. DE: 18; FR: 12; NL: 1 rok; UK: 2 lata Graduate.", uk: "Більшість країн ЄС дають 9–18 міс. на пошук роботи після диплома. DE: 18; FR: 12; NL: 1 рік; UK: 2 роки Graduate." } },
  { id: "schengen", short: "Yes",
    q: { en: "Can I travel through Schengen on my permit?", es: "¿Puedo viajar por Schengen con mi permiso?", fr: "Puis-je circuler dans Schengen avec mon titre ?", de: "Darf ich mit meinem Permit durch Schengen reisen?", it: "Posso viaggiare in Schengen con il permesso?", pt: "Posso viajar em Schengen com a autorização?", pl: "Czy mogę podróżować po Schengen z permitem?", uk: "Чи можу я подорожувати Шенгеном з посвідкою?" },
    answer: { en: "A residence permit from any Schengen country lets you travel to all 29 Schengen countries for up to 90 days in any 180-day period, for tourism. You can't work in another Schengen country without a separate permit.", es: "Un permiso de cualquier país Schengen te permite viajar a los 29 países hasta 90 días en 180, por turismo. No puedes trabajar en otro Schengen sin permiso aparte.", fr: "Un titre Schengen permet de circuler dans les 29 pays Schengen, 90 jours sur 180, en touriste. Pas de travail dans un autre pays Schengen sans permis distinct.", de: "Ein Aufenthaltstitel eines Schengen-Landes erlaubt Tourismus in allen 29 — 90 von 180 Tagen. Arbeit anderswo nur mit eigenem Permit.", it: "Un permesso di un paese Schengen consente turismo nei 29 paesi — 90 giorni su 180. Niente lavoro altrove senza permesso.", pt: "Autorização de qualquer país Schengen permite turismo nos 29 — 90 dias em 180. Trabalho noutro só com permissão própria.", pl: "Karta pobytu z dowolnego Schengen pozwala podróżować po 29 krajach — 90/180 dni. Praca w innym tylko z osobnym permitem.", uk: "Посвідка з будь-якої країни Шенгену дає туризм у 29 країнах — 90/180 днів. Робота в іншій — лише з окремим дозволом." },
    region: { en: "EU / Schengen", es: "UE / Schengen", fr: "UE / Schengen", de: "EU / Schengen", it: "UE / Schengen", pt: "UE / Schengen", pl: "UE / Schengen", uk: "ЄС / Шенген" } },
  { id: "family-join", short: "Usually yes",
    q: { en: "Can my partner join me?", es: "¿Puede venir mi pareja?", fr: "Mon/ma partenaire peut-il/elle me rejoindre ?", de: "Kann mein/e Partner/in nachziehen?", it: "Il mio partner può raggiungermi?", pt: "O meu parceiro pode juntar-se a mim?", pl: "Czy partner/ka może do mnie dołączyć?", uk: "Чи може партнер/ка приєднатися?" },
    answer: { en: "Most residence permits allow family reunification for spouses, registered partners and minor children. The sponsor usually has to prove enough income (typically the local minimum wage) and adequate housing. Processing can take 2–6 months.", es: "La mayoría permite reagrupación de cónyuges, parejas registradas e hijos menores. El sponsor suele probar ingresos (salario mínimo) y vivienda. Tarda 2–6 meses.", fr: "La plupart des titres permettent le regroupement pour conjoint, partenaire enregistré et enfants. Le garant prouve revenus (SMIC) et logement. 2–6 mois.", de: "Familiennachzug für Ehepartner, eingetragene Partner und minderjährige Kinder ist meist möglich. Sponsor weist Einkommen (Mindestlohn) und Wohnraum nach. 2–6 Monate.", it: "Quasi tutti i permessi consentono ricongiungimento per coniuge, partner registrato e figli minori. Sponsor: reddito (minimo) e alloggio. 2–6 mesi.", pt: "Quase todas as autorizações permitem reagrupamento de cônjuge, parceiro registado e filhos menores. Sponsor: rendimento (mínimo) e habitação. 2–6 meses.", pl: "Większość permitów umożliwia łączenie z małżonkiem, partnerem i dziećmi. Sponsor: dochód (płaca minimalna) i mieszkanie. 2–6 mies.", uk: "Більшість посвідок дозволяє возз'єднання з подружжям, зареєстрованим партнером і дітьми. Спонсор: дохід (мінімальна) та житло. 2–6 міс." } },
  { id: "drive", short: "It depends",
    q: { en: "Can I drive with my home country licence?", es: "¿Puedo conducir con mi carnet del país de origen?", fr: "Puis-je conduire avec mon permis d'origine ?", de: "Darf ich mit dem heimischen Führerschein fahren?", it: "Posso guidare con la patente del mio paese?", pt: "Posso conduzir com a minha carta de condução?", pl: "Czy mogę jeździć na prawie jazdy z kraju?", uk: "Чи можу я керувати з рідним посвідченням?" },
    answer: { en: "Inside the EU/EEA, your licence is valid as long as it's valid at home. From outside, most countries let you drive 6–12 months on your foreign licence (sometimes with an International Driving Permit) before requiring an exchange or local test.", es: "Dentro UE/EEE, vale mientras esté vigente. De fuera, casi todos permiten 6–12 meses (a veces con permiso internacional) antes de canjear o examinarse.", fr: "Dans l'UE/EEE, le permis est valable tant qu'il l'est au pays. Hors UE, 6–12 mois (parfois avec PCI) avant échange ou examen local.", de: "EU/EWR: gültig solange daheim gültig. Sonst meist 6–12 Monate (manchmal mit Int. Führerschein) vor Umtausch oder Prüfung.", it: "UE/SEE: valida finché lo è in patria. Da fuori: 6–12 mesi (a volte con permesso internazionale) prima di cambio o esame.", pt: "UE/EEE: válida enquanto válida em casa. De fora: 6–12 meses (às vezes carta internacional) antes de troca/exame.", pl: "UE/EOG: ważne dopóki ważne w kraju. Spoza: 6–12 mies. (czasem międzynarodowe) przed wymianą/egzaminem.", uk: "ЄС/ЄЕЗ: дійсне поки чинне вдома. Поза ЄС: 6–12 міс. (іноді з міжнародним) до обміну чи іспиту." } },
  { id: "open-bank", short: "Usually yes",
    q: { en: "Can I open a bank account before moving?", es: "¿Puedo abrir cuenta antes de mudarme?", fr: "Puis-je ouvrir un compte avant de partir ?", de: "Kann ich vor dem Umzug ein Konto eröffnen?", it: "Posso aprire un conto prima di trasferirmi?", pt: "Posso abrir conta antes de mudar?", pl: "Czy mogę założyć konto przed przeprowadzką?", uk: "Чи можу я відкрити рахунок до переїзду?" },
    answer: { en: "Digital banks (N26, Revolut, Wise, Bunq) let you open an account from abroad in minutes with just a passport. Traditional banks usually need your address registration first.", es: "Bancos digitales (N26, Revolut, Wise, Bunq) abren cuenta en minutos solo con pasaporte. Bancos tradicionales requieren registro de domicilio.", fr: "Néobanques (N26, Revolut, Wise, Bunq) : compte en quelques minutes avec passeport. Banques classiques : domicile requis.", de: "Digitalbanken (N26, Revolut, Wise, Bunq) öffnen Konten in Minuten nur mit Pass. Filialbanken brauchen meist Anmeldung.", it: "Banche digitali (N26, Revolut, Wise, Bunq) aprono in pochi minuti con passaporto. Banche tradizionali: serve la residenza.", pt: "Bancos digitais (N26, Revolut, Wise, Bunq) abrem em minutos só com passaporte. Tradicionais: precisam de morada.", pl: "Banki cyfrowe (N26, Revolut, Wise, Bunq) — konto w minuty z paszportem. Tradycyjne wymagają meldunku.", uk: "Цифрові банки (N26, Revolut, Wise, Bunq) — рахунок за хвилини з паспортом. Класичні вимагають реєстрації адреси." } },
  { id: "leave-return", short: "Usually no",
    q: { en: "Can I leave and re-enter while my permit is being processed?", es: "¿Puedo salir y volver mientras tramitan mi permiso?", fr: "Puis-je sortir et rentrer pendant le traitement du titre ?", de: "Darf ich während der Permit-Bearbeitung aus- und einreisen?", it: "Posso uscire e rientrare durante l'esame del permesso?", pt: "Posso sair e voltar enquanto a autorização é processada?", pl: "Czy mogę wyjechać i wrócić w trakcie rozpatrywania permitu?", uk: "Чи можна виїхати і повернутися під час оформлення посвідки?" },
    answer: { en: "Once you've applied for a residence permit, leaving the country before you get the card (or at least a fiktionsbescheinigung / récépissé) often means you can't re-enter. Always ask the immigration office for a re-entry confirmation first.", es: "Tras solicitar el permiso, salir antes de tener la tarjeta (o récépissé/Fiktionsbescheinigung) suele impedir reentrar. Pide siempre confirmación de reentrada.", fr: "Après dépôt, sortir avant d'obtenir la carte (ou récépissé/Fiktionsbescheinigung) empêche souvent de revenir. Demandez toujours une autorisation de réentrée.", de: "Nach Antragstellung kann Ausreise vor Erhalt der Karte (oder Fiktionsbescheinigung) die Wiedereinreise blockieren. Vorher Bestätigung einholen.", it: "Dopo la domanda, uscire prima della carta (o ricevuta) spesso impedisce il rientro. Chiedi sempre conferma di rientro.", pt: "Após pedido, sair antes do cartão (ou récépissé) muitas vezes impede o regresso. Peça sempre confirmação.", pl: "Po złożeniu wniosku wyjazd przed kartą (lub poświadczeniem) często blokuje powrót. Zawsze pytaj urząd.", uk: "Після подачі заяви виїзд до отримання картки (або довідки) часто блокує повернення. Завжди уточнюйте в офісі." } },
  { id: "marry-locally", short: "Yes",
    q: { en: "Can I get married to a local?", es: "¿Puedo casarme con alguien del país?", fr: "Puis-je me marier avec un·e local·e ?", de: "Darf ich eine/n Einheimische/n heiraten?", it: "Posso sposarmi con una persona del posto?", pt: "Posso casar com alguém local?", pl: "Czy mogę wziąć ślub z miejscowym?", uk: "Чи можу я одружитися з місцевим?" },
    answer: { en: "Foreigners can marry citizens in almost every country. You'll need a passport, a 'no impediment to marry' certificate from your home country (apostilled and translated), and sometimes a residence proof.", es: "Extranjeros pueden casarse con ciudadanos casi en todas partes. Necesitas pasaporte, fe de soltería apostillada y traducida, y a veces prueba de residencia.", fr: "Les étrangers peuvent presque partout épouser un·e citoyen·ne. Il faut passeport, certificat de non-empêchement (apostillé et traduit) et parfois preuve de résidence.", de: "Ausländer können fast überall Einheimische heiraten. Pass, Ehefähigkeitszeugnis (mit Apostille und Übersetzung), manchmal Wohnsitznachweis.", it: "Stranieri possono sposare cittadini quasi ovunque. Servono passaporto, nulla osta al matrimonio (con apostille e traduzione) e a volte residenza.", pt: "Estrangeiros podem casar com cidadãos quase em todo o lado. Passaporte, certidão de não-impedimento (apostilada/traduzida), por vezes morada.", pl: "Cudzoziemcy mogą poślubić obywateli niemal wszędzie. Paszport, zaświadczenie o zdolności do zawarcia małżeństwa (apostille + tłumaczenie), czasem meldunek.", uk: "Іноземці можуть одружитися з громадянами майже всюди. Паспорт, довідка про відсутність перешкод (з апостилем і перекладом), іноді — реєстрація." } },
  { id: "permanent-residency", short: "Usually yes",
    q: { en: "Can I get permanent residency?", es: "¿Puedo obtener residencia permanente?", fr: "Puis-je obtenir la résidence permanente ?", de: "Kann ich Daueraufenthalt bekommen?", it: "Posso ottenere la residenza permanente?", pt: "Posso obter residência permanente?", pl: "Czy mogę uzyskać pobyt stały?", uk: "Чи можу я отримати постійний дозвіл?" },
    answer: { en: "Most countries grant permanent residency after 5 years of continuous legal stay (EU long-term resident status). Germany: 21–33 months for skilled workers with B1 German. Spain: 5 years. Portugal: 5 years.", es: "La mayoría tras 5 años de estancia legal (residente UE de larga duración). DE: 21–33 meses con B1; ES: 5 años; PT: 5 años.", fr: "Souvent après 5 ans de séjour légal (résident UE longue durée). DE: 21–33 mois si B1 ; ES: 5 ans ; PT: 5 ans.", de: "Meist nach 5 Jahren legalem Aufenthalt (EU-Daueraufenthalt). DE: 21–33 Monate für Fachkräfte mit B1; ES/PT: 5 Jahre.", it: "Di solito dopo 5 anni di soggiorno legale (lungo soggiornante UE). DE: 21–33 mesi con B1; ES/PT: 5 anni.", pt: "Geralmente após 5 anos legais (residente UE longa duração). DE: 21–33 meses com B1; ES/PT: 5 anos.", pl: "Zwykle po 5 latach legalnego pobytu (rezydent długoterminowy UE). DE: 21–33 mies. dla wykwalifikowanych z B1; ES/PT: 5 lat.", uk: "Зазвичай після 5 років легального проживання (довгостроковий резидент ЄС). DE: 21–33 міс. для фахівців з B1; ES/PT: 5 років." } },
];

// ------- COST PRESETS + ROW LABELS + DISCLAIMER -------
export type CostPresetL = {
  id: string;
  label: Tx;
  visa: number; flight: number; housingDeposit: number; monthlyRent: number;
  insurance: number; translations: number; transport: number; initialSavings: number;
};
const COST_PRESETS_L: CostPresetL[] = [
  { id: "student-eu", visa: 75, flight: 200, housingDeposit: 800, monthlyRent: 500, insurance: 110, translations: 80, transport: 60, initialSavings: 1500,
    label: { en: "EU student", es: "Estudiante UE", fr: "Étudiant UE", de: "EU-Studierender", it: "Studente UE", pt: "Estudante UE", pl: "Student UE", uk: "Студент ЄС" } },
  { id: "student-us", visa: 200, flight: 800, housingDeposit: 2000, monthlyRent: 1200, insurance: 250, translations: 100, transport: 120, initialSavings: 3500,
    label: { en: "US student", es: "Estudiante EE.UU.", fr: "Étudiant US", de: "US-Studierender", it: "Studente USA", pt: "Estudante EUA", pl: "Student USA", uk: "Студент США" } },
  { id: "worker", visa: 150, flight: 500, housingDeposit: 1600, monthlyRent: 900, insurance: 90, translations: 120, transport: 100, initialSavings: 2500,
    label: { en: "Worker / expat", es: "Trabajador / expat", fr: "Salarié / expat", de: "Arbeitnehmer / Expat", it: "Lavoratore / expat", pt: "Trabalhador / expat", pl: "Pracownik / expat", uk: "Працівник / експат" } },
  { id: "nomad", visa: 250, flight: 700, housingDeposit: 1000, monthlyRent: 800, insurance: 80, translations: 50, transport: 80, initialSavings: 2000,
    label: { en: "Digital nomad", es: "Nómada digital", fr: "Nomade numérique", de: "Digitaler Nomade", it: "Nomade digitale", pt: "Nómada digital", pl: "Cyfrowy nomada", uk: "Цифровий кочівник" } },
];

const COST_ROWS_L: { id: keyof Omit<CostPresetL, "id" | "label">; label: Tx; max: number }[] = [
  { id: "visa", max: 600, label: { en: "Visa fees", es: "Tasas de visado", fr: "Frais de visa", de: "Visumgebühren", it: "Costi visto", pt: "Taxas de visto", pl: "Opłaty wizowe", uk: "Візові збори" } },
  { id: "flight", max: 2000, label: { en: "Flight / transport to country", es: "Vuelo / transporte al país", fr: "Vol / transport vers le pays", de: "Flug / Transport ins Land", it: "Volo / trasporto verso il paese", pt: "Voo / transporte para o país", pl: "Lot / transport do kraju", uk: "Переліт / транспорт до країни" } },
  { id: "housingDeposit", max: 5000, label: { en: "Housing deposit", es: "Fianza de vivienda", fr: "Caution logement", de: "Mietkaution", it: "Deposito alloggio", pt: "Caução de habitação", pl: "Kaucja mieszkaniowa", uk: "Заставa за житло" } },
  { id: "monthlyRent", max: 3000, label: { en: "First month rent", es: "Primer mes de alquiler", fr: "Premier mois de loyer", de: "Erste Miete", it: "Primo mese di affitto", pt: "Primeira renda", pl: "Pierwszy czynsz", uk: "Перший місяць оренди" } },
  { id: "insurance", max: 400, label: { en: "Insurance (1 month)", es: "Seguro (1 mes)", fr: "Assurance (1 mois)", de: "Versicherung (1 Monat)", it: "Assicurazione (1 mese)", pt: "Seguro (1 mês)", pl: "Ubezpieczenie (1 mies.)", uk: "Страхування (1 міс.)" } },
  { id: "translations", max: 400, label: { en: "Translations & apostilles", es: "Traducciones y apostillas", fr: "Traductions & apostilles", de: "Übersetzungen & Apostillen", it: "Traduzioni e apostille", pt: "Traduções e apostilas", pl: "Tłumaczenia i apostille", uk: "Переклади та апостилі" } },
  { id: "transport", max: 300, label: { en: "Local transport setup", es: "Configurar transporte local", fr: "Mise en place transport local", de: "Lokales Verkehrsticket einrichten", it: "Avvio trasporto locale", pt: "Transporte local inicial", pl: "Lokalny transport — start", uk: "Налаштування місцевого транспорту" } },
  { id: "initialSavings", max: 6000, label: { en: "Emergency savings to land with", es: "Ahorros de emergencia para llegar", fr: "Épargne d'urgence à l'arrivée", de: "Notrücklage zum Start", it: "Risparmi di emergenza all'arrivo", pt: "Poupanças de emergência à chegada", pl: "Rezerwa awaryjna na start", uk: "Резерв на старт" } },
];

const COST_DISCLAIMER: Tx = {
  en: "Estimates in EUR. Real costs vary by city and personal choices — use this as a starting point, not a quote.",
  es: "Estimaciones en EUR. Los costes reales varían por ciudad y elecciones — úsalo como punto de partida.",
  fr: "Estimations en EUR. Les coûts réels varient selon la ville et les choix — c'est un point de départ.",
  de: "Schätzungen in EUR. Echte Kosten variieren je nach Stadt und Entscheidungen — nur Ausgangspunkt.",
  it: "Stime in EUR. I costi reali variano per città e scelte — punto di partenza, non preventivo.",
  pt: "Estimativas em EUR. Custos reais variam por cidade e escolhas — apenas ponto de partida.",
  pl: "Szacunki w EUR. Realne koszty zależą od miasta i wyborów — to punkt wyjścia.",
  uk: "Оцінки в EUR. Реальні витрати залежать від міста та виборів — це лише орієнтир.",
};

// ------- COMPARE ROWS -------
export type CompareRowL = { country: Tx; flag: string; studentHours: Tx; visaTime: Tx; workRights: Tx };
const COMPARE_L: CompareRowL[] = [
  { flag: "🇩🇪",
    country: { en: "Germany", es: "Alemania", fr: "Allemagne", de: "Deutschland", it: "Germania", pt: "Alemanha", pl: "Niemcy", uk: "Німеччина" },
    studentHours: { en: "20h/week", es: "20 h/sem", fr: "20 h/sem", de: "20 Std./Wo.", it: "20 h/sett.", pt: "20 h/sem", pl: "20 godz./tydz.", uk: "20 год/тиж" },
    visaTime: { en: "1–3 mo", es: "1–3 meses", fr: "1–3 mois", de: "1–3 Monate", it: "1–3 mesi", pt: "1–3 meses", pl: "1–3 mies.", uk: "1–3 міс." },
    workRights: { en: "Open", es: "Abierto", fr: "Ouvert", de: "Offen", it: "Aperto", pt: "Aberto", pl: "Otwarte", uk: "Відкрито" } },
  { flag: "🇫🇷",
    country: { en: "France", es: "Francia", fr: "France", de: "Frankreich", it: "Francia", pt: "França", pl: "Francja", uk: "Франція" },
    studentHours: { en: "20h/week", es: "20 h/sem", fr: "20 h/sem", de: "20 Std./Wo.", it: "20 h/sett.", pt: "20 h/sem", pl: "20 godz./tydz.", uk: "20 год/тиж" },
    visaTime: { en: "~1 mo", es: "~1 mes", fr: "~1 mois", de: "~1 Monat", it: "~1 mese", pt: "~1 mês", pl: "~1 mies.", uk: "~1 міс." },
    workRights: { en: "Open", es: "Abierto", fr: "Ouvert", de: "Offen", it: "Aperto", pt: "Aberto", pl: "Otwarte", uk: "Відкрито" } },
  { flag: "🇳🇱",
    country: { en: "Netherlands", es: "Países Bajos", fr: "Pays-Bas", de: "Niederlande", it: "Paesi Bassi", pt: "Países Baixos", pl: "Holandia", uk: "Нідерланди" },
    studentHours: { en: "16h/week", es: "16 h/sem", fr: "16 h/sem", de: "16 Std./Wo.", it: "16 h/sett.", pt: "16 h/sem", pl: "16 godz./tydz.", uk: "16 год/тиж" },
    visaTime: { en: "2–4 wk", es: "2–4 sem", fr: "2–4 sem", de: "2–4 Wo.", it: "2–4 sett.", pt: "2–4 sem", pl: "2–4 tyg.", uk: "2–4 тиж." },
    workRights: { en: "Open", es: "Abierto", fr: "Ouvert", de: "Offen", it: "Aperto", pt: "Aberto", pl: "Otwarte", uk: "Відкрито" } },
  { flag: "🇪🇸",
    country: { en: "Spain", es: "España", fr: "Espagne", de: "Spanien", it: "Spagna", pt: "Espanha", pl: "Hiszpania", uk: "Іспанія" },
    studentHours: { en: "30h/week", es: "30 h/sem", fr: "30 h/sem", de: "30 Std./Wo.", it: "30 h/sett.", pt: "30 h/sem", pl: "30 godz./tydz.", uk: "30 год/тиж" },
    visaTime: { en: "1–2 mo", es: "1–2 meses", fr: "1–2 mois", de: "1–2 Monate", it: "1–2 mesi", pt: "1–2 meses", pl: "1–2 mies.", uk: "1–2 міс." },
    workRights: { en: "Open", es: "Abierto", fr: "Ouvert", de: "Offen", it: "Aperto", pt: "Aberto", pl: "Otwarte", uk: "Відкрито" } },
  { flag: "🇸🇪",
    country: { en: "Sweden", es: "Suecia", fr: "Suède", de: "Schweden", it: "Svezia", pt: "Suécia", pl: "Szwecja", uk: "Швеція" },
    studentHours: { en: "Unlimited", es: "Ilimitado", fr: "Illimité", de: "Unbegrenzt", it: "Illimitato", pt: "Ilimitado", pl: "Bez limitu", uk: "Без обмежень" },
    visaTime: { en: "1–3 mo", es: "1–3 meses", fr: "1–3 mois", de: "1–3 Monate", it: "1–3 mesi", pt: "1–3 meses", pl: "1–3 mies.", uk: "1–3 міс." },
    workRights: { en: "Open", es: "Abierto", fr: "Ouvert", de: "Offen", it: "Aperto", pt: "Aberto", pl: "Otwarte", uk: "Відкрито" } },
];

const COMPARE_HEAD: Record<string, Tx> = {
  country: { en: "Country", es: "País", fr: "Pays", de: "Land", it: "Paese", pt: "País", pl: "Kraj", uk: "Країна" },
  studentHours: { en: "Student hrs", es: "Horas est.", fr: "Heures étud.", de: "Studi-Std.", it: "Ore studio", pt: "Horas estud.", pl: "Godz. student.", uk: "Год. студ." },
  visaTime: { en: "Visa time", es: "Tiempo visado", fr: "Délai visa", de: "Visumdauer", it: "Tempo visto", pt: "Tempo visto", pl: "Czas wizy", uk: "Час візи" },
  workRights: { en: "Work", es: "Trabajo", fr: "Travail", de: "Arbeit", it: "Lavoro", pt: "Trabalho", pl: "Praca", uk: "Робота" },
};

const COMPARE_NOTE: Tx = {
  en: "Data is indicative and updated periodically. Always verify with the official embassy or consulate before making decisions.",
  es: "Datos orientativos, actualizados periódicamente. Verifica siempre con la embajada o consulado oficial.",
  fr: "Données indicatives, mises à jour régulièrement. Vérifiez toujours auprès de l'ambassade ou du consulat.",
  de: "Hinweisende, regelmäßig aktualisierte Daten. Immer mit Botschaft/Konsulat verifizieren.",
  it: "Dati indicativi, aggiornati periodicamente. Verifica sempre con ambasciata o consolato.",
  pt: "Dados indicativos, atualizados periodicamente. Verifique sempre com a embaixada ou consulado.",
  pl: "Dane orientacyjne, aktualizowane okresowo. Zawsze sprawdź w ambasadzie lub konsulacie.",
  uk: "Дані орієнтовні, оновлюються періодично. Завжди перевіряйте в посольстві чи консульстві.",
};

// ------- HELP -------
const HELP_L = {
  pageSubtitle: { en: "Quick contacts and clear steps for the moments that matter.", es: "Contactos rápidos y pasos claros para los momentos clave.", fr: "Contacts rapides et étapes claires pour les moments qui comptent.", de: "Schnelle Kontakte und klare Schritte für entscheidende Momente.", it: "Contatti rapidi e passi chiari per i momenti importanti.", pt: "Contactos rápidos e passos claros para os momentos importantes.", pl: "Szybkie kontakty i jasne kroki na ważne chwile.", uk: "Швидкі контакти й чіткі кроки для важливих моментів." } as Tx,
  quickContacts: { en: "Quick contacts", es: "Contactos rápidos", fr: "Contacts rapides", de: "Schnellkontakte", it: "Contatti rapidi", pt: "Contactos rápidos", pl: "Szybkie kontakty", uk: "Швидкі контакти" } as Tx,
  lostHeader: { en: "Lost passport — what to do", es: "Pasaporte perdido — qué hacer", fr: "Passeport perdu — que faire", de: "Pass verloren — was tun", it: "Passaporto perso — cosa fare", pt: "Passaporte perdido — o que fazer", pl: "Zgubiony paszport — co robić", uk: "Втрачений паспорт — що робити" } as Tx,
  tipLabel: { en: "Tip", es: "Consejo", fr: "Astuce", de: "Tipp", it: "Suggerimento", pt: "Dica", pl: "Wskazówka", uk: "Порада" } as Tx,
  tipText: { en: "Keep a digital copy of your passport, visa, and insurance card in your phone — Borderless will soon let you store them encrypted.", es: "Guarda una copia digital del pasaporte, visado y seguro en tu móvil — Borderless pronto los cifrará.", fr: "Conservez une copie numérique de passeport, visa et assurance — Borderless les chiffrera bientôt.", de: "Bewahre digitale Kopien von Pass, Visum und Versicherung im Handy auf — bald verschlüsselt in Borderless.", it: "Tieni una copia digitale di passaporto, visto e assicurazione nel telefono — Borderless le cifrerà presto.", pt: "Guarda cópia digital de passaporte, visto e seguro no telemóvel — Borderless cifra em breve.", pl: "Trzymaj cyfrową kopię paszportu, wizy i ubezpieczenia w telefonie — Borderless wkrótce je zaszyfruje.", uk: "Зберігайте цифрову копію паспорта, візи та страховки в телефоні — Borderless скоро шифруватиме." } as Tx,
  emergencyTitle: { en: "Emergency", es: "Emergencia", fr: "Urgence", de: "Notruf", it: "Emergenza", pt: "Emergência", pl: "Alarm", uk: "Екстрено" } as Tx,
  emergencyNote: { en: "EU-wide emergency line", es: "Emergencias en toda la UE", fr: "Numéro d'urgence européen", de: "EU-weite Notrufnummer", it: "Numero d'emergenza UE", pt: "Linha de emergência UE", pl: "Numer alarmowy UE", uk: "Єдиний номер ЄС" } as Tx,
  lostTitle: { en: "Lost passport", es: "Pasaporte perdido", fr: "Passeport perdu", de: "Pass verloren", it: "Passaporto perso", pt: "Passaporte perdido", pl: "Zgubiony paszport", uk: "Втрачений паспорт" } as Tx,
  lostValue: { en: "Step-by-step", es: "Paso a paso", fr: "Étape par étape", de: "Schritt für Schritt", it: "Passo per passo", pt: "Passo a passo", pl: "Krok po kroku", uk: "Покроково" } as Tx,
  lostNote: { en: "Report, file, request emergency travel doc", es: "Denuncia, registra, pide documento de viaje urgente", fr: "Déclarer, enregistrer, demander un titre d'urgence", de: "Melden, anzeigen, Notreisedokument beantragen", it: "Denuncia, registra, richiedi documento di viaggio d'emergenza", pt: "Denuncie, registe, peça documento de viagem urgente", pl: "Zgłoś, zarejestruj, poproś o dokument awaryjny", uk: "Заявити, оформити, отримати тимчасовий документ" } as Tx,
  embassyTitle: { en: "Find embassy", es: "Encontrar embajada", fr: "Trouver l'ambassade", de: "Botschaft finden", it: "Trova ambasciata", pt: "Encontrar embaixada", pl: "Znajdź ambasadę", uk: "Знайти посольство" } as Tx,
  embassyValue: { en: "Locator", es: "Localizador", fr: "Localisateur", de: "Suche", it: "Localizzatore", pt: "Localizador", pl: "Lokalizator", uk: "Пошук" } as Tx,
  embassyFallback: { en: "Set your trip on the home screen to personalize", es: "Configura tu viaje en el inicio para personalizar", fr: "Définissez votre voyage sur l'accueil pour personnaliser", de: "Setze deine Reise im Start, um zu personalisieren", it: "Imposta il viaggio dalla home per personalizzare", pt: "Defina a viagem no início para personalizar", pl: "Ustaw podróż na ekranie głównym, by spersonalizować", uk: "Налаштуйте поїздку на головному екрані" } as Tx,
  embassyTemplate: { en: "Nearest {from} consulate in {to}", es: "Consulado de {from} más cercano en {to}", fr: "Consulat de {from} le plus proche en {to}", de: "Nächstes {from}-Konsulat in {to}", it: "Consolato di {from} più vicino in {to}", pt: "Consulado de {from} mais próximo em {to}", pl: "Najbliższy konsulat {from} w {to}", uk: "Найближче консульство {from} у {to}" } as Tx,
  euTitle: { en: "EU Immigration Portal", es: "Portal de Inmigración UE", fr: "Portail immigration UE", de: "EU-Einwanderungsportal", it: "Portale Immigrazione UE", pt: "Portal de Imigração UE", pl: "Portal Imigracyjny UE", uk: "Імміграційний портал ЄС" } as Tx,
  euNote: { en: "Official guidance", es: "Guía oficial", fr: "Guide officiel", de: "Offizielle Hinweise", it: "Guida ufficiale", pt: "Orientação oficial", pl: "Oficjalne wytyczne", uk: "Офіційні рекомендації" } as Tx,
  steps: [
    { en: "Stay calm. Note the time and place where you last had your passport.", es: "Mantén la calma. Anota cuándo y dónde tuviste el pasaporte por última vez.", fr: "Restez calme. Notez quand et où vous aviez votre passeport pour la dernière fois.", de: "Ruhig bleiben. Notiere Zeit und Ort, wo der Pass zuletzt da war.", it: "Mantieni la calma. Annota dove e quando avevi il passaporto.", pt: "Mantenha a calma. Anote onde e quando teve o passaporte.", pl: "Zachowaj spokój. Zapisz kiedy i gdzie ostatnio miałeś paszport.", uk: "Зберігайте спокій. Запишіть, де і коли востаннє був паспорт." },
    { en: "Report the loss to the local police and ask for a written report.", es: "Denuncia ante la policía local y pide informe escrito.", fr: "Signalez la perte à la police locale et demandez un procès-verbal écrit.", de: "Verlust bei der Polizei melden und schriftlichen Bericht verlangen.", it: "Denuncia alla polizia locale e richiedi rapporto scritto.", pt: "Denuncie à polícia local e peça relatório escrito.", pl: "Zgłoś stratę policji i poproś o pisemny raport.", uk: "Заявіть у місцеву поліцію та отримайте письмовий протокол." },
    { en: "Contact your country's embassy or consulate to start an emergency travel document.", es: "Contacta a tu embajada/consulado para iniciar un documento de viaje urgente.", fr: "Contactez votre ambassade/consulat pour un titre de voyage d'urgence.", de: "Botschaft/Konsulat kontaktieren, um Notreisedokument zu beantragen.", it: "Contatta ambasciata/consolato per un documento di viaggio d'emergenza.", pt: "Contacte embaixada/consulado para documento de viagem urgente.", pl: "Skontaktuj się z ambasadą/konsulatem po awaryjny dokument podróży.", uk: "Зверніться до посольства/консульства для тимчасового документа." },
    { en: "If you have travel insurance, notify them — many cover replacement fees.", es: "Si tienes seguro de viaje, avísales — muchos cubren la reemisión.", fr: "Si vous avez une assurance voyage, prévenez-la — beaucoup couvrent les frais.", de: "Reiseversicherung informieren — viele übernehmen Ersatzkosten.", it: "Informa l'assicurazione di viaggio — molte coprono la sostituzione.", pt: "Avise o seguro de viagem — muitos cobrem reemissão.", pl: "Powiadom ubezpieczenie podróżne — wiele pokrywa koszty.", uk: "Повідомте туристичне страхування — багато покривають витрати." },
  ] as Tx[],
};

// ------- HOOK -------
export function useLocalizedExtras() {
  const [lang] = useLang();
  return useMemo(() => {
    const T = (t: Tx | undefined) => pk(t, lang);
    const A = (a: Tx[] | undefined) => (a ? a.map((t) => pk(t, lang)) : []);
    return {
      lang,
      terms: TERMS_L.map((e) => ({
        id: e.id,
        term: T(e.term),
        bureaucratic: T(e.bureaucratic),
        plain: T(e.plain),
        example: e.example ? T(e.example) : undefined,
        aliases: e.aliases ?? [],
      })),
      legal: LEGAL_L.map((q) => ({
        id: q.id,
        q: T(q.q),
        short: q.short,
        answer: T(q.answer),
        region: q.region ? T(q.region) : undefined,
        source: q.source,
      })),
      costPresets: COST_PRESETS_L.map((p) => ({ ...p, label: T(p.label) })),
      costRows: COST_ROWS_L.map((r) => ({ id: r.id, max: r.max, label: T(r.label) })),
      costDisclaimer: T(COST_DISCLAIMER),
      compareRows: COMPARE_L.map((r) => ({
        flag: r.flag,
        country: T(r.country),
        studentHours: T(r.studentHours),
        visaTime: T(r.visaTime),
        workRights: T(r.workRights),
      })),
      compareHead: {
        country: T(COMPARE_HEAD.country),
        studentHours: T(COMPARE_HEAD.studentHours),
        visaTime: T(COMPARE_HEAD.visaTime),
        workRights: T(COMPARE_HEAD.workRights),
      },
      compareNote: T(COMPARE_NOTE),
      help: {
        subtitle: T(HELP_L.pageSubtitle),
        quickContacts: T(HELP_L.quickContacts),
        lostHeader: T(HELP_L.lostHeader),
        tipLabel: T(HELP_L.tipLabel),
        tipText: T(HELP_L.tipText),
        emergencyTitle: T(HELP_L.emergencyTitle),
        emergencyNote: T(HELP_L.emergencyNote),
        lostTitle: T(HELP_L.lostTitle),
        lostValue: T(HELP_L.lostValue),
        lostNote: T(HELP_L.lostNote),
        embassyTitle: T(HELP_L.embassyTitle),
        embassyValue: T(HELP_L.embassyValue),
        embassyFallback: T(HELP_L.embassyFallback),
        embassyTemplate: T(HELP_L.embassyTemplate),
        euTitle: T(HELP_L.euTitle),
        euNote: T(HELP_L.euNote),
        steps: A(HELP_L.steps),
      },
    };
  }, [lang]);
}